### ISSUE TITLE
Compare function with exhaustive pattern matching

### ISSUE THREAD

**Issue by citizen428** [fsharp/fslang-suggestions#801] opened 2019-10-28 02:03 UTC
# Compare function with exhaustive pattern matching

I propose we add a `compare` function that's similar to the one defined in Haskell's Prelude, which returns `LT`, `EQ` or `GT` respectively.

The existing way of approaching this problem in F# is using something like `compare x y |> sign` and matching on -1, 0, and 1 respectively, which isn't an exhaustive match.

## Pros and Cons 

The advantages of making this adjustment to F# that we could get an exhaustive match on orderings.

The disadvantages of making this adjustment to F# are that it adds new functionality which may not be useful too enough people, therefore not worth the effort.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): XS

Related suggestions: This seems to be made somewhat unnecessary the comparison patterns mentioned in #793. Instead of 

```fsharp
match (compare a b) with
| LT -> ...
| EQ -> ...
| GT -> ...
```

we could have something like 

```fsharp
match a with 
| < b -> ...
| > b ->
| _ ->
```

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by citizen428** [comment] 2019-10-28 02:07
Somehow my original search missed #661, which I guess means this has been discussed and declined, sorry for the noise. Will leave open just in case.

**Comment by cartermp** [comment] 2019-10-29 17:16
Thanks, sorry for not noticing that this was a duplicate of #661.

**Closed by cartermp** 2019-10-29 17:16 UTC
