### ISSUE TITLE
resolve the Some/None names in a type-directed way

### ISSUE THREAD

**Issue by KevinRansom** [fsharp/fslang-suggestions#874] opened 2020-06-04 23:18 UTC
# resolve the Some/None names in a type-directed way

I propose we resolve the Some/None names in a type-directed way" ?

That is, "match v with Some x -> a | None -> b" will resolve even if "v" is a value option?

The existing way of approaching this problem in F# is to have new Names ValueSome and ValueNone

## Pros and Cons 

The advantages of making this adjustment to F# are ...
Right now, every PR that uses ValueOption increase the use of ValueSome and ValueNone in the code, it is a jarring syntax to review and one where we have feedback about using "Option" because "the cost of a reference is not that much".  Well sometimes it is.

The disadvantages of making this adjustment to F# are ...
I don't know what they might be, beyond making it tougher to reason about whether the type implementing the option is reference or value.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): NA

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [*] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [*] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [*] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [*] This is not a breaking change to the F# language design
* [ * I or my company would be willing to help implement and/or test this

**Comment by Swoorup** [comment] 2020-06-05 00:12
Could this alleviate the need for Value* in the future? 

https://github.com/ltrzesniewski/dotnet-runtime/blob/master/docs/design/features/object-stack-allocation.md

**Comment by KevinRansom** [comment] 2020-06-05 00:42
@Swoorup 

Stack allocation of objects in that feature, are to enable stack allocation of objects that exist only for the duration of that method call ... See the section on Escape Analysis, I have snipped a portion for your review, the last sentence is the killer:
<snip>
An object is said to escape a method if it can be accessed after the method's execution has finished. An object allocation can be moved to the stack safely only if the object doesn't escape the allocating method.
</snip>

**Comment by smoothdeveloper** [comment] 2020-06-05 02:56
@KevinRansom I like this idea on the paper, somehow feel the `struct` tuples would be a great candidate for same treatment.

Now, what would be the implication of enabling this only for few select types with some internal compiler magic versus making it a more open ended system that users can leverage?

It goes along similar lines with #737 where a literal type can't be determined just by looking at the literal.

I think doing any of the feature blurring those lines enable the other suggestions achieving the same for some other subset of types, I'm not yet clear if this is too much and should be stopped in it's track or if I want all.

Haskell has the concept of ["overloaded strings literals" extension](https://www.schoolofhaskell.com/user/kseo/overloaded-string-literals) (and probably others) and I think it makes sense, although I see the tension with how F# works today.

**Comment by KevinRansom** [comment] 2020-06-08 19:09
@zpodlovics the proposal, isn't about changing the types, it's about allowing ValueOptions access to the good names.  That is, when the compiler knows that the developer is operating on ValueOptions, it can allow the names None and Some to be used as in the place of VSome and VNone.  The benefit of that is that it reduces the churn in source when a developer spots an opportunity to replace an Option with a ValueOption.  It also eliminates the code review opinion "Please just use 'Option' because I don't like to see 'VSome and VNone' all over the codebase.

**Comment by charlesroddie** [comment] 2020-07-14 08:37
> it can allow the names None and Some to be used as in the place of VSome and VNone

Actually VSome and VNone can't be used currently as far as I can tell.

![image](https://user-images.githubusercontent.com/19760720/87403699-217fd680-c5b5-11ea-80f4-2913f97fe5ef.png)

Allowing VSome and VNone and VOption as aliases of ValueSome, ValueNone, and ValueOption would be a good solution.

**Comment by iriri** [comment] 2021-03-05 08:01
Aliasing the `ValueOption` module as `VOption` would be an obvious step if the above were to be done. The ability to alias discriminated union constructors in general would be nice too. (`Choice1Of2`, etc. come to mind.)

**Comment by dsyme** [comment] 2021-03-11 13:39
> Aliasing the ValueOption module as VOption would be an obvious step if the above were to be done. The ability to alias discriminated union constructors in general would be nice too. (Choice1Of2, etc. come to mind.)

This is a reasonable sugestion

**Comment by dsyme** [comment] 2021-09-20 14:06
Resolving as duplicate of https://github.com/fsharp/fslang-suggestions/issues/1074

**Closed by dsyme** 2021-09-20 14:06 UTC

**Comment by charlesroddie** [comment] 2024-01-13 18:54
I don't think the linked issue is relevant @dsyme . The linked issue concerns matching only, and would be relevant to the matching part of this issue if `Some` were the name of a `ValueOption` case, but it isn't.

I had pushback on PRs which increased use of ValueOptions, even though no complexity was added and performance (GC pressure) would be reduced, because of the extra typing involved.

To split up my suggestion above, if we can get 80% there by only typing `V` instead of `Value` that would be a great solution. An extra `v` for everything is explicit and consistent.

1. Specifying types: already done in the `voption` alias.
2. Allowing construction with `VSome` and `VNone`: easy and would be good to add to the standard library.
3. Allowing matching with `VSome` and `VNone`: the tricky part. Doing this as an active pattern would presumably involve more work for the compiler and more work at runtime with an extra voption created. Could the principle of type aliases apply to DU cases?
4. Aliasing the ValueOption module - not sure not sure if modules can be aliased at present, will check when at a computer.
