### ISSUE TITLE
suggest: Tuple Field Metadata

### ISSUE THREAD

**Issue by greatim** [fsharp/fslang-suggestions#616] opened 2017-10-27 00:53 UTC
https://github.com/fsharp/fslang-design/blob/master/FSharp-4.1/FS-1006-struct-tuples.md,
in the section **Possible Extension: Tuple Field Metadata**
> e.g.

>`let f () = struct (x=1,y=1)`

It's hard to  distinguish if 'x=1' is a bool or a int named 'x' .

I suggest to add the metadata into the signature of function.
e.g.
`let f(): struct(x: int * y: int) = struct(1, 1)`

**Comment by dsyme** [comment] 2017-11-16 12:34
Duplicate of  #207

**Closed by dsyme** 2017-11-16 12:34 UTC
