### ISSUE TITLE
Add syntactic (_ + 1) sugar for functions ala Scala/Clojure

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#186] opened 2016-10-20 01:50 UTC
**Submitted by Khan Thompson on 3/21/2014 12:00:00 AM**  
**37 votes on UserVoice prior to migration**  

Add in shorthand syntax for anonymous functions, even if it is only for single argument functions.
For example:

```
[1; 2; 3; 4] |> List.map (_ + 1)
```

As opposed to

```
[1; 2; 3; 4] |> List.map (fun i -> i + 1)
```

It would be great to have this shorthand so that our anonymous functions are shorter than the C#ers' :).

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5665355)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5665355-add-syntactic-sugar-for-functions-ala-scala-cloju.md#comments)

**Comment by charlesroddie** [comment] 2020-01-01 13:56
Presumably `g(f(_+1))` would mean `g(f(fun i -> i+1))`, resolving to the closest bracket, but `g(f <| _+1)` would mean `g(fun i -> f(i+1))`. People would find this confusing. It will be hard to find a bracketing rule that is both consistent and unsurprising. Even something simple like `(_+(1+_))` I believe would generate a lot of interpretations. If the notation didn't use round brackets then this problem would go away, but F# currently restricts itself to ascii characters and all the suitable ones got taken straight away.

Some suggestions in https://github.com/fsharp/fslang-suggestions/issues/168 are intermediate approaches to the same problem (shorter syntax for `fun x ->`) which are more readable and don't give the same ambiguities.

**Comment by dsyme** [comment] 2022-06-16 15:43
Treating this as a duplicate of https://github.com/fsharp/fslang-suggestions/issues/634

**Closed by dsyme** 2022-06-16 15:43 UTC
Labels: area: syntax
