### ISSUE TITLE
Allow omitting the space in nameof(System.String.Join<_> :string*_->_)

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#963] opened 2021-01-20 15:47 UTC
# Allow omitting the space in `nameof(System.String.Join<_> :string*_->_)`

Because `>:` seems to parse together, we have the same scenario as `let inline r< ^T> = Unchecked.defaultof< ^T>` where `<^` are parsed together and must be separated with space.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Less visual clutter
2. Less unexpected errors that span the entire file due to lexing

The disadvantages of making this adjustment to F# are (none)

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment] 2021-01-22 11:36
Suggest closing as too small

**Comment by Happypig375** [comment] 2021-01-22 14:59
Small improvements are still improvements.

**Comment by cartermp** [comment] 2021-01-24 18:02
closing as a duplicate of https://github.com/fsharp/fslang-suggestions/issues/668

**Closed by cartermp** 2021-01-24 18:02 UTC
