### ISSUE TITLE
The type annotation as prefix

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#1183] opened 2022-09-09 01:10 UTC
I propose we add a new way to construct records, where the type precedes the literal body of the record.

```F#
type Point = {x:int;y:int}
type Vector = {x:int;y:int}

let p = 
    Point {x=1;y=2} 
    // rec<Point> {x=1;y=2} 
    //new<Point> {x=1;y=2}
```

The existing way of approaching this problem in F# is 

```F#
let p = {x=1;y=2}:Point
```

## Pros and Cons 

The advantages of making this adjustment to F# are 
  - Conforms to the order of brain thinking from overview to detail
  - when input `new<Point>` , IDE will Can prompt out all fields.

The disadvantages of making this adjustment to F# are ...

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [ ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [ ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by abelbraaksma** [comment] 2022-09-09 02:55
I’m afraid this proposal violates a fundamental principle for new features: adding more ways to do something.

But, more importantly, it’s already possible. The more idiomatic way of writing this (and in fact, the formatted Fantomas will automatically fix it this way) is:

```
let p: Point = {x=1;y=2}
```

> Conforms to the order of brain thinking from overview to detail

that’s why above syntax is preferred

> when input new<Point> , IDE will Can prompt out all fields.

That’s what the ide does with above syntax. Though in most cases you won’t be needing any type specification anyway, it’s relatively rare to need to do so, as the types are inferred (unless there’s a conflicting definition as in your example).

**Comment by xp44mm** [comment] 2022-09-09 03:13
@abelbraaksma thanks for your code. 

yes! how about:

```F#
printf "%A" ({x=1;y=2}:Point)
```

**Comment by xp44mm** [comment] 2022-09-09 03:31
> btw, new itself already has a different semantic meaning and is used for disposables and constructors. Neither applies here. We should not reassign different meanings to it. Just my 2p.

how about this:

```F#
Point ::: {x=1;y=2}
```

**Comment by RonaldSchlenker** [comment] 2022-09-09 06:41
There is already this syntax to specify the type:

```fsharp
let p = { Point.x = 1; y = 2 }
let v = { Vector.x = 1; y = 2 }
```

**Comment by RonaldSchlenker** [comment] 2022-09-09 06:44
BTW, record construction is also discussed in [this suggestion](https://github.com/fsharp/fslang-suggestions/issues/722).

**Comment by abelbraaksma** [comment] 2022-09-09 13:19
> yes! how about:
> `printf "%A" ({x=1;y=2}:Point)`

Nothing wrong with this. I wouldn't write it that way, but it is fine. Certainly you are not proposing to change this to `printf "%A" (new <Point> {x=1;y=2})`? it is more wordy, and harder to read, plus it repurposes `new`, as said before _and_ it uses `<'T>` which is used for generics, and suddenly gets a whole different meaning.

I believe there used to be OCaml syntax if you didn't use `#light` that allowed `printf "%A" (Point({x=1;y=2}))` or `printf "%A" ((Point) {x=1;y=2})` as in C#. But most F# programmers have shied away from using the slightly weird OCaml way of type prefixes (again: not sure I have the syntax right, but a syntax like that used to work in some version of F#).

I think if you have types like that and find yourself using postfix type specification a lot, you may want to rethink the model you're having. Also, `printf "%A" ({Point.x=1;y=2})` was pointed out above by @RonaldSchlenker and works for the "left-to-right" style of reading.

**Comment by theprash** [comment] 2022-09-09 13:28
I sometimes use `id<_>` as a convenient way to do type annotation as prefix or without parens. It's a bit weird but it works nicely and is already available:

```fsharp
let p = id<Point> {x=1;y=2}
```

**Comment by abelbraaksma** [comment] 2022-09-09 13:29
Oh, here's a thought. Looks like the syntax _does_ already exist, and you can create any function you want to do this:

```
let f() = printfn "%A" (id<Point> { x = 12; y = 13})
let f() = printfn "%A" (id<Vector> { x = 12; y = 13})
```

If you don't like to use `id`, you can define anything:

```
let newly<'T> x = id<'T> x
let f() = printfn "%A" (newly<Vector> { x = 12; y = 13})
```

**Comment by xp44mm** [comment] 2022-09-10 01:31
@theprash thank you! That's exactly the answer I wanted.

```F#
type Point = {x:int;y:int}
type Vector = {x:int;y:int}

let p = id<Point> {x=1;y=2}
```

**Comment by abelbraaksma** [comment] 2022-09-10 12:32
Both methods are fine, you can choose whichever you find most convenient. Do note that they are technically different (function call vs type annotation, either implicit or explicit).

Though if you can write your types such that they don’t need any of this, it’s gonna be easier to code. Either use different field names, place them in different modules or namespaces, or use type aliases. This won’t always be possible, but it’ll keep your code cleaner if you can.

**Comment by charlesroddie** [comment] 2022-09-11 14:29
> BTW, record construction is also discussed in #722.

Should close this thread as a duplicate of that one (since access to the constructor would achieve the objectives of the OP).

**Closed** 2022-09-15 08:49 UTC
