### ISSUE TITLE
Records are converted to or from each other

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#943] opened 2020-12-29 05:24 UTC
# Records are converted to or from each other

I propose we Records can be converted to each other. to borrow to use its custom members. 

```F#
type Point2d = 
    {
        x:float
        y:float
    }
    member this.totuple = (this.x,this.y)

type Point3d = 
    {
        x:float
        y:float
        z:float
    }

    member this.totuple = (this.x,this.y,this.z)

let p2d = {x=3.0;y=4.0}
let p3d = {x=3.0;y=4.0;z=0.0}

let z = 6.0

// static method
// 2 to 3
let pp3d = Point3d.from {|
    yield! p2d
    yield z
    //z = 3.0; // or
|}


// 3 to 2
let pp2d = Point2d.from {|
    yield! p3d
|}

let pp2d = Point2d.from p3d

// instance method:
let p2d = p3d.to<Point2d>

let p3d = {|
    yield! p2d
    yield z
    //z = 3.0; // or
|}.to<Point3d>

```

target no exist member will be ignored. when conflict, the later wins. missing member will fail.

## Pros and Cons 

This allows for better modularity, with programmers focusing only on the current record. The fields of the record often have same name conflicts, so the name of the record type occurency is also important. for example the `Vector2d` same as `Point2d`.

**Comment by ScottHutchinson** [comment] 2020-12-29 18:24
So you want the compiler to generate explicit `from` and `to` member functions for record types that have some fields in common?

**Comment by xp44mm** [comment] 2020-12-30 01:04
We want to use the duck type when passing data, ignoring the specific name of the type. When you use the functionality of type binding, you use a named type.

**Comment by yatli** [comment] 2020-12-30 15:21
interfaces?

**Comment by vzarytovskii** [comment] 2020-12-30 17:03
Yeah, I think intefaces or codegen will be more sutable here, rather than having an implicit conversion support.

**Comment by cartermp** [comment] 2020-12-30 19:23
Closing as a duplicate of https://github.com/fsharp/fslang-suggestions/issues/898

I will post another answer in there showing how you can achieve some of what you are after

**Closed by cartermp** 2020-12-30 19:23 UTC
