### ISSUE TITLE
Do not allow byref and outref in assert

### ISSUE THREAD

**Issue by PythonSmith** [fsharp/fslang-suggestions#927] opened 2020-10-05 07:33 UTC
# Do not allow byref and outref in assert

I propose we do not allow using byref and outref in the expression of a assert statement.
The following code would not be allowed anymore:
```fsharp
let s = "2"
let mutable i = 0
assert Int32.TryParse(s, &i)
// Fails only in release builds
Trace.Assert <| (i = Int32.Parse(s))
```

## Pros and Cons 

The advantages of making this adjustment to F# are that it prevents easily made mistakes of assert which are not trivial to find out because it's not reproducible on debug builds.

The disadvantages of making this adjustment to F# are previous code using this bad pattern will break.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by abelbraaksma** [comment] 2020-10-05 09:19
> The advantages of making this adjustment to F# are that it prevents easily made mistakes of assert which are not trivial to find out because it's not reproducible on debug builds.

Isn't this true for basically anything you're doing with `assert`? It is specifically meant to apply _only to debug builds_. So if you have `assert (x / 0)` it'll crash in debug build and succeed in release build.

The same argument could be applied for `#if DEBUG` code blocks. If people do not want differences between release builds and debug builds they shouldn't use these mechanisms, or, in the case of `assert` place them in unit testsl.

**Comment by cartermp** [comment] 2020-10-05 15:17
> This is not a breaking change to the F# language design

This suggestion is, by definition, a breaking change because it explicitly calls for a coding pattern to no longer compile.

Given that this doesn't appear to cause significant harm and the feature works as designed, I'll close this.

**Closed by cartermp** 2020-10-05 15:17 UTC
