### ISSUE TITLE
Undercore is used for constructor type name

### ISSUE THREAD

**Issue by xp44mm** [fsharp/fslang-suggestions#1222] opened 2023-01-03 01:01 UTC
from https://github.com/dotnet/fsharp/issues/14514
I propose we

```fsharp
let x = ([]:int _)
let x = ([]:_<int>)
```

The existing way of approaching this problem in F# is

```fsharp
let x = ([]:int list)
let x = ([]:list<int>)
```

Although very rare, there are some use cases:

```fsharp
type T<'a> = 
    {
        ls: 'a list
    }

    static member zero =
        {
            ls = ([]:'a list)
        }

let rec loop t =
    if t = T<'a>.zero then
        ()
    else loop t

```

`T` may be a very complex nested structure. Defining `zero` will make the `loop` code very clear.

## Pros and Cons 

The advantages of making this adjustment to F# are

Reduce code redundancy

The disadvantages of making this adjustment to F# are ...

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment] 2023-01-04 01:26
Duplicate of #850 and is rejected due to infeasibility

**Comment by cartermp** [comment] 2023-01-04 16:03
Closing as a dupe

**Closed by cartermp** 2023-01-04 16:03 UTC

**Comment by xp44mm** [comment] 2023-01-05 00:42
It is a duplicate of the closed issue and is not counted as a duplicate.
