### ISSUE TITLE
Allow type declaration with `sig` on code/script files

### ISSUE THREAD

**Issue by noralambda** [fsharp/fslang-suggestions#1382] opened 2024-09-02 18:01 UTC
**I propose we** ... (describe your suggestion here)

`sig` could be used for type declaration in script and code files.

Examples:

```fsharp
sig foo : int -> float -> string in
let foo a b = 
    //...
``` 

```fsharp
sig x : Person in
let x = {Name=10; Age=5}
```

```fsharp
type Foo() = 
    sig member A : () -> 'X in
    member _.A () = // ...

    sig member B : 'X in
    member val B = // ...
```

`in` should be optional on Recursive Modules.

I feel this syntax for class member signature is weird. Help?

Multiple declaration should be considered error:
```fsharp
sig bar : float -> float -> int in
let bar a (b:float) = // Error
    // ...
```

## Pros and Cons 

**The advantages of making this adjustment to F# are** 

Code becomes easier to read and reason about

## Extra information

**Estimated cost (XS, S, M, L, XL, XXL):**  

**Related suggestions:** (put links to related suggestions here)
#341

## Affidavit (please submit!)

Please tick these items by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [StackOverflow](http://stackoverflow.com)) and I have searched StackOverflow for discussions of this issue
* [x] This is a language change and not purely a tooling change (e.g. compiler bug, editor support, warning/error messages, new warning, non-breaking optimisation) belonging to [the compiler and tooling repository](https://github.com/dotnet/fsharp)
* [x] This is not something which has obviously "already been decided" in previous versions of F#. If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by T-Gro** [comment] 2024-09-03 08:41
Duplicate of https://github.com/fsharp/fslang-suggestions/issues/341 , which was closed as "probably not".

**Comment by T-Gro** [comment] 2024-09-03 08:42
Closing comment: https://github.com/fsharp/fslang-suggestions/issues/341#issuecomment-1506752584

**Comment by vzarytovskii** [comment] 2024-09-03 09:02
Yeah, I think it's essentially the same. Also, personally don't like adding another keyword (which is quite unfamiliar), `val` would've been better (which was also rejected). I am going to close this one.

@dsyme please reopen if your opinion on this changed.

**Closed by vzarytovskii** 2024-09-03 09:02 UTC
