### ISSUE TITLE
Match anonymous record's type inference with nominal records inference

### ISSUE THREAD

**Issue by gusty** [fsharp/fslang-suggestions#759] opened 2019-06-23 07:52 UTC
I propose we use the same type of inference as for nominal records

The way it works now is that anonymous records inference occurs at a later stage.

## Pros and Cons 

The advantages of making this adjustment to F#:  Currently because anonymous records are inferred at a later stage they are more prone to be type annotated than nominal records, which defeats the whole purpose of having anonymous records.

The disadvantages of making this adjustment to F#: Nominal records inference is considered a bit weird because when two records contain the same field names, the compiler takes the last one that was declared.

## Extra information

Estimated cost: M 

Related suggestions: https://github.com/dotnet/fsharp/issues/6699

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by kspeakman** [comment] 2019-11-14 18:40
I think my comment applies here, but if I need to make a separate issue let me know.

We ran into this today. We were forced to twist our code into a particular shape in order to make anonymous records worth using.

```fsharp
type MyThing =
    { MyName: string
      MyStatus: MyStatus }

async {
    match! Db.read<{| Name: string; Status: string |}> config query with
    | Error ex -> ...
    | Ok list ->
        // does not compile, cannot determine type of item
        let toStatus item =
            { MyName = item.Name
              MyStatus = MyStatus.fromString item.Status }
        return Ok (List.map toStatus list)
}
```

Here's how I had to make it work:

```fsharp
async {
    match! Db.read<{| Name: string; Status: string |}> config query with
    | Error ex -> ...
    | Ok list ->
        let returnList =
            list
            |> List.map (fun item ->
                { MyName = item.Name
                  MyStatus = MyStatus.fromString item.Status }
            )
        return Ok returnList
}
```

_This is not the actual code, but an example for demonstration._

This 2nd example was enough for type inference to determine the type of `item`. But I had to twist my code into a different shape (that I do not prefer) to reap any benefit from using anonymous records. I could have made the first code listing work if I had added a type annotation to the anonymous record. However, at that point it wouldn't be worth using it over a static record type. And this use case (an interim, internal type) seems like exactly the kind of reason for anonymous records to exist.

This would be solved if anonymous record type definitions were exposed to the type inference engine inside the scope where they are declared. So that the type inference would realize without annotation that the `item` fit the anonymous record type. Then I would have been able to use the first code example, which is cleaner to my eyes.

**Comment by gusty** [comment] 2019-11-14 21:15
@cartermp  Any update on this?
Does it make sense? Could it be approved for F# 5 ?
I know record inference is considered a bit weird, but it's been around since the beginning, let's don't bring completely different rules for anons.

**Comment by dsyme** [comment] 2019-11-21 11:52
This is by-design based on the RFC, and I don't immediately expect we will change we can change it

**Comment by dsyme** [comment] 2019-11-21 11:54
> But I had to twist my code into a different shape (that I do not prefer) to reap any benefit from using anonymous records. 

This is correct - the anonymity of anonymous records doesn't come without cost, nor do they give benefits in all situations. In general, type annotations are required to get decent name resolution and comprehensible errors for `x.Name` constructs.   There are many cases where defining a record instead makes sense and may result in simpler and clearer code

**Comment by kspeakman** [comment] 2019-11-21 17:44
Our team has attempted to use anonymous records in place of transient records and tuples multiple times, but with no discernible benefit so far. It seems our code base just doesn't have or we lack instincts to recognize the beneficial use cases.

**Comment by cartermp** [comment] 2019-11-21 18:01
The

```fsharp
List.someFn (fun x -> ...) myType
```

vs.

```fsharp
myType |> List.someFn (fun x -> ...)
```

Isn't limited to anonymous records by any means here, though. This is a general F# tension point.

**Comment by kspeakman** [comment] 2019-11-21 18:39
@cartermp Yes, that is a general ergonomic issue. But in this case, the first code listing would have worked by only replacing the anonymous type with a regular type. Because type inference would be aware of a regular type in the whole scope of the function, but not so for anonymous types.

**Comment by dsyme** [comment] 2019-11-21 19:11
>  Because type inference would be aware of a regular record definition for the toStatus function, but not so for anonymous records.

You can also define an anonymous record type abbreviation and use a type annotation.  It's essentially the same as defining a record type though

> Our team has attempted to use anonymous records in place of transient records and tuples multiple times, but with no discernible benefit so far.

Yes, this is a feature people will try to use in various ways and it won't always give the results the user hopes for.  I wrote this up somewhere, though it's not specifically in the RFC, but basically as soon as you need type annotations on code consuming the data then you may as well have defined a record type.  This is a major reason why the RFC talks so much about "a smooth path to nominalization", so you don't get trapped in using anon records in sophisticated ways, and then pay an enormous cost to back out.

That is, you may have experimented with them and decided not to use them, but I assume at least you didn't get stuck in a corner where it was effectively impossible or very costly to back out of that experiment.

**Comment by kspeakman** [comment] 2019-11-21 20:50
> This is a major reason why the RFC talks so much about "a smooth path to nominalization", so you don't get trapped in using anon records in sophisticated ways, and then pay an enormous cost to back out.

So it seems rather the purpose is to start out anonymous, such as in a REPL or data exploration. Then later go back and solidify into named records. That makes sense. And I suppose we assumed differently of them because we don't have those uses at present.

**Comment by gusty** [comment] 2019-11-22 08:47
> So it seems rather the purpose is to start out anonymous, such as in a REPL or data exploration. > Then later solidify into named records as needed. 

Well, actually that's exactly my scenario. I'm trying to use them in ad-hoc queries in a REPL and they don't work, replacing them by nominal records solves the issue, but it doesn't makes any sense.

It's really sad, because I was always pushing to get anon records in F#, in order to get these kind of queries working, which defeats the purpose of using F# as opposed to C# in Linqpad.

If there's a solid decision of not matching the type inference mechanism of nominal records, is there a way to improve this type inference? Maybe using multipass inference, as it's being discussed in #594 ?

**Comment by dsyme** [comment] 2019-11-22 14:50
>I'm trying to use them in ad-hoc queries in a REPL and they don't work

Could you clarify - do you mean they don't work (unexpected), or that they require more type annotations than is palatable?  I assume the latter.

> which defeats the purpose of using F# as opposed to C# in Linqpad.

AFAIK inference for linqpad-like scenarios should be at least as good as for C# intra-method inference for anonymous C# objects, and likely better.  Could you give examples if not?

thanks

**Comment by gusty** [comment] 2019-11-22 21:02
Yes, I meant they require type annotations.
There are some SRTPs involved that fails, probably because they are being resolved before the type of the record, but with nominal records this is not a problem.
I will try to create a minimal repro of the problem.

**Comment by dsyme** [comment] 2023-04-12 15:21
Closing per my comment here: https://github.com/fsharp/fslang-suggestions/issues/759#issuecomment-557052071

This is all really by design

**Closed by dsyme** 2023-04-12 15:21 UTC
Labels: area: anonymous-records
