### ISSUE TITLE
Fix this DU type inference scoping bug

### ISSUE THREAD

**Issue by sgtz** [fsharp/fslang-suggestions#570] opened 2017-05-16 01:07 UTC
# Fix this DU type inference scoping bug

fix this confused most-recent namespace bug. NB. we could get around this if we could inherit from a DU. However, this is not possible because there are no constructors.

```fsharp
open Microsoft.FSharp.Reflection

let caseLabel (x:'x) = 
    typeof<'x> |> fun typ ->
      if FSharpType.IsUnion(typ) 
          then FSharpValue.GetUnionFields(x, typ) ||> fun case _ -> Some(case.Name)
          else None

type Option<'t> = 
  | Some of 't
  | None
  override x.ToString() = 
    match caseLabel x with
    | Some(x) -> x
    | None    -> "None"  
 
sprintf "%A" <| (Some 1)  
sprintf "%A" <| (None) 
```

This question derived from a StackOverflow question, so it may happen from time to time in the wild, particularly for people moving across from C#.

See: http://stackoverflow.com/questions/43981211/print-case-identifier-of-discriminated-union

## Pros and Cons 

The advantages of making this adjustment to F# are ...

more predictable behaviour for OO-style code + the way the .Net ecosystem expects certain conventions to work (such as .ToString()). 

We can't extend generically defined discriminated unions (or presumably, other constructorless structures).

The disadvantages of making this adjustment to F# are ...

From the F#-only perspective, it's not a big problem. The time to make it happen might be better spent elsewhere. Redefining something might become awkward.

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to reated suggestions here)

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [ ] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [ X ] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [ X ] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ X ] This is not a breaking change to the F# language design
* [ ] I would be willing to help implement and/or test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment] 2017-11-16 13:43
I'm closing this one as by design, I don't see the specific request for change here? Thanks!

**Closed by dsyme** 2017-11-16 13:43 UTC

**Comment by sgtz** [comment] 2017-11-16 22:24
there are quirks that F# people get used to that could be a bit more seamless in terms of the .NET platform. The aim here was to help iron some of these out, or at least to document them. 

i.e. it'd be nice to be able to override ToString. Nothing more to it than that. It's a simple low impact observation/request. I've heard it more than once, and yet, I personally tend not to care (if I happened to care for a particular case, I'd adjust the FSI pretty printing... but that's a little more advanced... nothing quick-grab about that). 

Probably this "quick-grab" familiarity category is more important to someone getting used to F#, or beginning their journey as a programmer, but does that make it a less important request? It's easy for experienced people (me included) to overlook how frustrating quirks can be to newcomers. Does this come down to eventually being thankful for opinionated design, or is it a rough edge that could easily be sanded down? 

Also, note that this request was thrown together quickly in order to capture the need. For a more considered explanation, hit me up on email or Skype to discuss further if you are interested. 

My larger concern is more for the set of rough edges than this request as such. It might be easier just to work on the F# compiler and quietly submit these kinds of less glorious fixes. This particular issue may have side effects. i.e. we don't want inheritance by design (that's what Scala is for), and yet, it'd still be nice to override.ToString(). Is there another mechanism, or another way forward? Or is it simply by design and too bad.

**Comment by realvictorprm** [comment] 2017-11-17 09:01
You misunderstand the purpose of the DU's. They are in general designed in such a way that all information included as case name and case parameters are going to be printed if to string is being called. 

Do you have a specific case when you really would need a different string representation? If so, it might be even better to keep the standard representation and create a function which creates your very case specific string representation (seeing that it's very unlikely that the other cases of the DU wouldn't need special treatment then).

**Comment by realvictorprm** [comment] 2017-11-17 09:03
Also, DU's must not be always multiple classes so far I know so one cannot just translate the cases down to a class (and so matching would always be needed)

**Comment by sgtz** [comment] 2017-11-17 10:00
@realvictorprm: I get (understand) and love DUs. At least I've got a pretty good grasp on them. I raise this on behalf of a new C#er testing the F# waters. Your "it might be even better" logic is sound. I agree there. The gist of this request is, are there ways to be more sympathetic to other language idioms -- primarily C#. The prefered ways you or I might go for are not going to be obvious. In fact, these preferences might even get in the way of a good initial experience. What does it take to be a good .NET citizen? Are we doing all that we can? Do you / we remember what it was like when picking up F# for the first time? Did you already have a tonne of C# experience?

Sensible defaults and opinions are great... but are we sometimes too extreme in adhering to these within a broader context.

Probably there's a study that could be done -- of these 200 "rough edges", 20 of them are too opinionated. Fix those, and well, that leads to easier language onboarding.

Think about it like this -- ToString overriding works practically everywhere in C#. Come to F#, and now it doesn't. When "universal truths" break, it's jarring.  Yes, we've got a functional rationale for why this or that is unnecessary, but, you know, does it really matter in the wider context of language adoption? Maybe it does. Maybe these opinions are what makes F# special, and the message to new folk is, "sorry... some things won't work like you expect them to, but trust me, you'll like it." 

"I'm not sure," is my answer. I have suspicions. Some of this is observation, and some of it is thinking out loud.
