### ISSUE TITLE
Allow units of measure in for loops

### ISSUE THREAD

**Issue by marklam** [fsharp/fslang-suggestions#534] opened 2017-02-09 11:38 UTC
# Allow units of measure in for loops

I propose we extend the for loop typing to allow looping over an integer with units of measure.
Currently, the following won't compile:
```
let maximumDistance = 3<km>
let minimumDistance = 1<km>
for trial = minimumDistance to maximumDistance do
    goRunning (trial * 1<km>)
```

The existing way of approaching this problem is to cast away the units of measure, and multiply them back in within the loop, which is ugly and reduces the safety that uom adds.

## Pros and Cons 

Advantages:

-  An improvement to the usefulness of units of measure

Disadvantages:
- Maybe this would make loop optimization more tricky?

## Extra informtion

Estimated cost (XS, S, M, L, XL, XXL): 
S to M ?

Related suggestions: (put links to reated suggestions here)
[Allow units of measure in sequence ranges #535](https://github.com/fsharp/fslang-suggestions/issues/535)

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help test this
* [ ] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by rmunn** [comment] 2017-02-20 02:34
As someone mentioned in #535, the `for` loop in this suggestion can currently be written as follows:

```fsharp
let maximumDistance = 3<km>
let minimumDistance = 1<km>
for trial in minimumDistance .. 1<km> .. maximumDistance do
    goRunning trial
```

Note that there's no need to cast `trial` inside the loop in this version, because it now has the unit of measure `km`.

However, it would still be nice to be able to do `for trial in minimumDistance .. maximumDistance` or `for trial = minimumDistance to maximumDistance` without having to explicitly specify the step as a UoM. This seems like a case where the compiler *should* be able to Do The Right Thing automatically, inferring the correct unit of measure for `trial` and for the step.

**Comment by dsyme** [comment] 2017-03-01 15:47
I'll close this as a duplicate of https://github.com/fsharp/fslang-suggestions/issues/535 since they are closely related with similar workarounds

**Closed by dsyme** 2017-03-01 15:47 UTC
