### ISSUE TITLE
readonly constructors for pattern matching

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#982] opened 2021-02-19 15:03 UTC
# readonly constructors for pattern matching

We could not pattern match in types with private constructors

```fsharp
module M =
    type Foo = private Foo of string 
    type Bar = private { Bar: string } 

open M
let foo (Foo f) = f // error
let bar ({Bar = b}) = b // error
```

So, we have to create functions to get the value and I usually use active patterns to have the same usage of a public constructor in pattern matching

```fsharp
module Foo =
    type Foo = private Foo of string 
    let get (Foo f) = f
let (|Foo|) f = Foo.get f

let foo (Foo f) = f // works
```

My proposal is to instead of `private` we have a `readonly` modifier.
Something like this:

```fsharp
module M =
    type Foo = readonly Foo of string 
    type Bar = readonly { Bar: string } 

open M
let foo (Foo f) = f // shoud work
let bar ({Bar = b}) = b // should work
```

## Pros and Cons 

Pros: Simpler domain modelling with types

Cons: more keywords

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment] 2021-02-19 16:26
Duplicate of https://github.com/fsharp/fslang-suggestions/issues/852

**Comment by cartermp** [comment] 2021-02-19 22:24
Thanks for noticing @Happypig375 

I will close this in favor of https://github.com/fsharp/fslang-suggestions/issues/852

Note there is rationale for not really doing this sort of thing here: https://github.com/fsharp/fslang-suggestions/issues/852#issuecomment-600046341

I am sympathetic to the "keep it simple" approach and feel that active patterns are a pretty good compromise, since you're stepping outside the default use case of records with this sort of approach

**Closed by cartermp** 2021-02-19 22:24 UTC
