### ISSUE TITLE
Use struct version of Tuple in inlined code

### ISSUE THREAD

**Issue by wanton7** [fsharp/fslang-suggestions#642] opened 2018-01-31 21:34 UTC
# Use struct version of Tuple in inlined code

Add compiler optimization to convert Tuple to ValueTuple in inlined version of code when possible. Maybe by converting all Tuples to struct version when they are only used inside a function.
If ValueTuple isn't compatible enough with Tuple then create struct version of Tuple to FSharp.Core and use it.

## Pros and Cons 
Advantage is that some of Tuple allocations might be avoided and this will help lessen GC pressure.

Only disadvantage is Release build might be slower because of this optimization.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  I have no idea

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

**Comment by wanton7** [comment] 2018-02-01 06:47
Submitted draft by accident, now suggestion is fixed.

**Comment by realvictorprm** [comment] 2018-02-01 07:53
Thanks' was wondering about the mail.

I think this sounds like a realistic optimization but don't know whether there could be something blocking this.

**Comment by charlesroddie** [comment] 2018-03-10 20:28
This [test](http://vaskir.blogspot.co.uk/2016/05/upcoming-f-struct-tuples-are-they.html) suggests the optimization might not be an improvement in cases where tuples are short lived or when the compiler optimizes away the tuples automatically.

**Comment by cartermp** [comment] 2019-01-21 03:43
The downside to something like this would be that if the compiler couldn't optimize the tuples away in the first place, code could be complex enough to incur the extra cost of copying the struct tuples, which incurs more CPU time.

Reference tuples are typically small enough to be allocated and collected in gen0 which is stupendously fast. Promotion to other generations, where a slower GC time is guaranteed, is likely going to be due to either:

* Also carrying larger objects with them
* Being allocated like crazy

In both cases I'm not convinced that using a struct tuple helps. In the former, the struct tuple carrying larger objects doesn't really benefit from being a struct. In the latter, the problem is likely to be user code rather than lacking this particular optimization.

Given this, I'm going to close this one out. I doubt such an optimization would help matters in a general case. However, if someone were to give convincing evidence that this helps a fairly wide variety of cases, I'm happy to re-open.

**Closed by cartermp** 2019-01-21 03:43 UTC
Labels: area: type-checking-and-inference, probably not
