### ISSUE TITLE
[bug] Error on function parameter that's readonlyspan<byte>

### ISSUE THREAD

**Issue by Xyncgas** [fsharp/fslang-suggestions#1209] opened 2022-11-16 10:20 UTC
![image](https://user-images.githubusercontent.com/35312807/202153801-3d119d66-6b30-4905-b052-a1a7f3bdface.png)
this's ok
![image](https://user-images.githubusercontent.com/35312807/202154580-4dd40889-98c8-417f-a05d-7b5963d67a90.png)
that's not ok

**Comment by Happypig375** [comment] 2022-11-16 11:53
This is expected because ReadOnlySpan is a byref struct and cannot be a generic type parameter which allows generic fields violating the requirements of byref structs, i.e. being stack-only. Here, `let Import = Serialization.Import` makes `Import` a value of type `ReadOnlySpan<byte> -> Secret` which is a generic instantiation of `'a -> 'b` (function type). This is not a bug though the error message could be made clearer.

**Comment by vzarytovskii** [comment] 2022-11-16 12:15
Gonna close it, since it's by design. I

**Closed** 2022-11-16 12:15 UTC
