### ISSUE TITLE
Allow manual merging of fields in multi-case struct unions

### ISSUE THREAD

**Issue by debugnik** [fsharp/fslang-suggestions#1004] opened 2021-05-06 15:22 UTC
# Allow manual merging of fields in multi-case struct unions

I propose we allow developers to manually merge fields in multi-case struct unions by reusing the same name across cases. This addresses the situation where some fields represent the same value in multiple cases. For example, the `Key` field would be merged in the following:

```f#
[<Struct>]
type KeyEvent =
    | KeyReleased of Key: Key
    | KeyPressed of Key: Key * IsRepeat: bool
```

For fields to be merged, they'd need to have the same type. Different reference types could potentially be merged too by storing them in a backing field of type `obj` (or their erased union type as per [FS-1092](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1092-anonymous-type-tagged-unions.md)).

This suggestion is a simple alternative to #699 (approved-in-principle!), but can be implemented without blocking it or similar generalizations, as they would subsume manual merging without any source changes.  So I think this suggestion could be a good interim solution, since that suggestion hasn't seen much progress.

The existing way of approaching this problem in F# is implementing a regular struct with a discriminator field and treat it as a union type manually. When the shared fields are common to all cases, it's also possible to factor them out to another type that holds both the shared fields and the remaining union value.

## Pros and Cons 

The advantages of making this adjustment to F# are:

- It enables efficient representations of F# struct unions.
- The properties emitted for merged fields are predictable.
- It allows future generalizations of field merging without source changes.

The disadvantages of making this adjustment to F# are:

- It requires work on type checking between fields and modifying the codegen.
- Work on this could eventually be dropped after a future generalization.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestion: Merge fields of the same type on multi-case union structs #699

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by dsyme** [comment] 2023-04-13 12:18
Given https://github.com/fsharp/fslang-suggestions/issues/699 has been approved I'll close this as a duplicate of that

**Closed by dsyme** 2023-04-13 12:18 UTC
Labels: area: structs-byrefs-and-span
