### ISSUE TITLE
Simplier operator partial application

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#955] opened 2021-01-14 20:13 UTC
# Simplier operator partial application

I'm playing with some Haskell and I noted that when partial apply an operator I don't need to wrap the operator in brackets before applying the first argument. I think we could have this.

Instead of use 

```fsharp
let numbers = [1; 2; 3; 4]
let numberPlusOne = List.map ((+)1) numbers 
```

We could use
```fsharp
let numbers = [1; 2; 3; 4]
let numberPlusOne = List.map (+1) numbers 
```

## Pros and Cons 

The advantages of making this type o operation better to read

I can't figure out any problem with this.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 
 I really don't know, if someone helps me to understand how hard it could be would be nice

## Affidavit (please submit!)
Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by kevmal** [comment] 2021-01-14 20:37
This is currently valid F# and poses challenges to the suggestion

```
let (~+) x _ =  x
let one = 1
let numbers = [1; 2; 3; 4]
let numberPlusOne = List.map (fun x -> x + one) numbers 
let numberPlusOne2 = List.map (+one) numbers 
```

**Comment by Tarmil** [comment] 2021-01-15 08:40
@kevmal Since currently F# relies on whitespace to disambiguate `(+)` and `(~+)` in normal operator calls:

```fsharp
x + y = (+) x y
f +y = f ((~+) y)
```

It would make sense to implement operator sections similarly:

```fsharp
(+ x) = fun y -> (+) y x
(+x) = (~+) x
```

But it would indeed be a breaking change, since currently `(+ x)` with a space also means `(~+) x`.

**Comment by gusty** [comment] 2021-01-15 08:51
@lucasteles  note that the example you gave is not 100% equivalent, I mean for `+` yes but just because is commutative.

What I mean is `List.map ((+)1) numbers` in not exactly `List.map (+1) numbers` in Haskell, it's rather `List.map (1+) numbers` and this is what makes it interesting, as we can express `List.map ( / 2 ) numbers` (divide all number by two) which in F# is not possible without using a lambda or a `flip` combinator.

If this is also part of your suggestion, this is a duplicate of #404

**Comment by ronaldschlenker** [comment] 2021-01-15 08:59
If we had #506, the benefit of this suggestion (at least in the use cases above) would be smaller, because we could write:

```fsharp
myList |> List.map (_ + 1)
```
which is quite close.

**Comment by gusty** [comment] 2021-01-15 09:01
Yes, but it seems it's not planned to support those cases.

**Comment by gusty** [comment] 2021-01-15 09:13
Maybe in order not to make it a breaking change we can support this feature for operators that are not "prefixable", like `/`.

Prefixable operators starts with `+`, `-`, `%` and `&`. Only `-` and `%` are not commutative which will be the only unfortunate cases where we can't take advantage of this feature.

**Comment by davidglassborow** [comment] 2021-01-15 13:09
I don't think we want to copy haskell here, in the rare case I want to partially apply an operator, the extra parenthesis are helpful to draw my attention to it.

**Comment by lucasteles** [comment] 2021-01-15 13:32
@kevmal I didn't know `(~+)`

@davidglassborow Maybe it depends on the domain, I use than a lot

@gusty you right, I think that could be part of the suggestion too, I can't find why the #404 was declined, but if is because of breaking changing maybe we could think in other way.

What do you guys think of an alternative way to partially apply operators?

Something like:
```fsharp
List.map {1+} [1;2;3]
// or
List.map '1+ [1;2;3]
```

Of curse, it would add some ~maybe unnecessary~ complexity to the language

**Comment by amieres** [comment] 2021-01-17 19:09
BTW this is what I do:

    /// swap: for use with operators: [1..5] |> List.map (__ (/) 2)
    let inline __   f a b = f b a

that way this is possible:

    [1..5] |> List.map (__ (/) 2)

**Comment by cartermp** [comment] 2021-01-24 18:18
> The advantages of making this type o operation better to read

I actually feel the opposite, I'm used to unary operators like `-` not requiring parentheses.

**Comment by abelbraaksma** [comment] 2021-02-24 15:43
I think the only viable way of moving this forward is by allowing infix operators to be used as postfix, which would then imply the missing argument and return a lambda.

Unary prefix operators are currently illegal as postfix, so it wouldn't pose a problem to the parser. 

```f#
List.map 1+
// is then equal to
List.map ((+) 1)
```

Though adding the concept of postfix operators to the language is by no means an easy feat...

**Comment by dsyme** [comment] 2022-06-14 16:29
Closing as we won't be doing the original suggestion

**Closed by dsyme** 2022-06-14 16:29 UTC
