### ISSUE TITLE
Type Provider Wilderness Mode

### ISSUE THREAD

**Issue by voronoipotato** [fsharp/fslang-suggestions#709] opened 2018-12-04 16:55 UTC
# Type Provider Wilderness Mode

Most of the world has unreliable access to internet connectivity. This is simply a fact of life, even for upper middle class families in America and many other nations. These people shouldn't be deprived access to our good good feature the type provider.

I propose we add a mode to F# projects such that if I am in an area with an unreliable access to an internet connection I can ALWAYS use my type providers. I would explicitly request the generation of my types and they would stay available until I request them again where it would run and generate my types no matter how that type provider was designed. I could then distribute my generated types to my peers who also live without reliable internet. This should work for all type providers, including databases, everything. I don't care if these types take up an extra 10 gigs on my file system or an extra 4 gigs of memory. I don't care that the resource might change out from under me and invalidate my types when I update my provider, that's simply a fact of life for people with unreliable internet access.  If I don't have reliable internet access like most of the world type providers as they exist now are not usable. I may not be able to run this code yet but at least I can write it and see whether it would even build. Or maybe I can run it on some sample data that I chose to serialize. 

The existing way of approaching this problem in F# is nonexistent , unless the type provider designer specifically built their type provider for your use case there is no recourse. An entire population should not be at the mercy of the designer of a particular type provider to design with accessibility in mind. 

## Pros and Cons 

The advantages of making this adjustment to F# are ...
- Increased accessibility of the language. 
- Network outages would not stop development.
- People whose only internet access is a McDonald's WiFi wouldn't be prohibited from using this language feature. Do NOT tell me you can just sit in a McDonald's for 6 hours, they will call the cops also I'm pretty sure you would contract some kind of sickness depending on the McD's.

The disadvantages of making this adjustment to F# are ...
- none that I'm aware of

## Extra information
You can test this by generating types and then going out into the woods for a weekend and seeing how far you get. You are allowed to update your types via mobile connection or McDonald's WiFi but your data budget is 20 dollars. For many this would be the data budget for the month.

Estimated cost (XS, S, M, L, XL, XXL): 
S???

I don't care how sloppy you do it, serialize the whole thing to disk whatever you need to do. You could even have a command line program that generates and serializes the types to file. 

Related suggestions: (put links to related suggestions here)
7sharp9 mentioned the use of AST in type providers may be helpful/relevant here? If you want gas money to go to the woods to program so you can get the real experience I'll happily pitch in. I think the lack of distraction and temptations will make you a convert to my ways. Sitting on a big rock with a solar panel backpack on a mountaintop programming F#, living the dream.
## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [+] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [+] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [+] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [+] This is not a breaking change to the F# language design
* [+] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment] 2019-01-03 15:46
Another way to look at this is that it could be used to make the use of TPs generally faster, but with dropping some correctness when working with remote resources.

**Comment by abelbraaksma** [comment] 2019-01-03 17:19
Apart from 'wilderness', many production systems, including the ones of my customers, limit access to most of all IP addresses outside their domain for security reasons. I wasn't aware of this limitation, and I remember using the CSV type provider locally, so I'm a little surprised this is even a consideration. Can't we (or the user of type provider X) simply use a URI Resolver that resolves whatever you have http(s)/ftp to some local resource?

**Comment by cartermp** [comment] 2019-01-03 17:23
@abelbraaksma I think what you're after can be covered by a type provider implementation (e.g., FSharp.Data) rather than within the mechanism itself. I think the distinction between this and what a given TP can handle on its own is subtle - in fact, I'm not sure I understand that distinction myself. Especially since you can download a resource and just point the type provider at that resource on your machine.

**Comment by abelbraaksma** [comment] 2019-01-03 17:39
@cartermp, if any given implementation can solve this, how is this then a language suggestion for F#? I feel like I'm missing the point. Does someone have an example of what can actually *not* be done presently that would be resolved once this suggestion were implemented? Isn't this something for library developers to consider?

**Comment by cartermp** [comment] 2019-01-03 17:53
I personally feel that this is not needed for many scenarios - if you can download the resource you're working with, all type providers will work perfectly well today. The issue is if you want to work without an internet connection to a resource that is too large for your machine, or one that cannot be placed on your machine for some reason. It's that situation where you'd want to have provided types cached on your machine somewhere.

**Comment by ReedCopsey** [comment] 2019-01-03 18:02
@cartermp That's taking a pretty limited view of this. Things like DB type providers can't always have a local copy of the full DB - same with type providers that work off sources like world bank, etc. 

For CSV/JSON/etc, local copies are great.

That being said, this _could_ be implemented in 3 different places:

1. A type provider can cache this themselves. (Status quo, though realistically none do - but many have the option of working off a local source instead.)
2. The TP SDK could build a caching layer that TPs could opt into.
3. The compiler could implement caching.

All 3 have potential advantages and disadvantages, though, tbh, the current scenario (1.) seems to be adding the most duplication and difficulty, especially as caching isn't always simple.

I'd personally love to see this as a layer in the SDK that could be opted into, as it'd be the most flexible without having to change the compiler API. Building into the compiler itself, in theory, could be the biggest perf win in the long run, though.

**Comment by voronoipotato** [comment] 2019-01-04 03:46
I understand that for like caching data you may have no option but to defer to the creator of the type provider to some extent, and that would also be okay.

**Comment by voronoipotato** [comment] 2019-01-25 15:35
Thank you for taking the time to consider and respond Don :).

**Comment by dsyme** [comment] 2023-04-12 14:36
Closing per my comments above

**Closed by dsyme** 2023-04-12 14:36 UTC
Labels: area: type-providers
