### ISSUE TITLE
Allow extension interfaces

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#182] opened 2016-10-20 01:49 UTC
**Submitted by Ryan Riley on 3/21/2014 12:00:00 AM**  
**92 votes on UserVoice prior to migration**  

Rather than just supporting single methods or properties, provide a mechanism by which to implement interfaces on existing types. This could be similar to protocols in Clojure and Elixir.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5665042)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5665042-allow-extension-interfaces.md#comments)

**Comment by dsyme** [comment] 2016-10-29 16:26
Treating this as a duplicate of #243

**Closed by dsyme** 2016-10-29 16:26 UTC
Labels: old votes:51-100
