### ISSUE TITLE
Can we build a pre-processor so we don't have to use the word: let ? Makes the function name standout and saves typing similar to R ?

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#88] opened 2016-10-20 01:36 UTC
# Can we build a pre-processor so we don't have to use the word: let ? Makes the function name standout and saves typing similar to R ? [13308666] #

**Submitted by Musa on 4/4/2016 12:00:00 AM**  
**4 votes on UserVoice prior to migration**  

Makes the function name standout and saves typing similar to R, ofcourse if it can be done without breaking something else ?
f := 3 //or ... rather than
let f = 3

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13308666)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-13308666-can-we-build-a-pre-processor-so-we-don-t-have-to.md#comments)

**Comment by dsyme** [comment] 2016-10-29 16:39
Duplicate of #218

**Closed by dsyme** 2016-10-29 16:39 UTC
Labels: old votes:0-10
