### ISSUE TITLE
Multiple pattern cases with 'when' clauses

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#715] opened 2019-01-20 13:02 UTC
# Multiple pattern cases with 'when' clauses

I propose we allow multiple patterns with 'when' to be or'ed together.

The existing way of approaching this problem in F# is using an if-statement or even duplicated code. 😢

Consider the following code:
```fs
type internal 'T memory = System.Memory<'T>
type internal chars = char memory

[<Struct>]
type UnicodeCharacter = private UnicodeCharacter of chars
module UnicodeCharacter =
    let Create (x:chars) =
        match x.Length with
        | 1 when x.Span.[0] |> System.Char.IsSurrogate |> not
        | 2 when x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate ->
            x |> UnicodeCharacter |> ValueSome
        | _ -> ValueNone
    let (|UnicodeCharacter|) (UnicodeCharacter x) = x
```
Currently the F# compiler errs out with the message
```
FS0010	Unexpected symbol '|' in pattern matching. Expected '->' or other token.
```
At the `|` in `| 2 when x.Span.[0]`.

I propose that we allow this instead of having to duplicate the case handling code, with a slight syntax change because `match 1 with | 2 | 1 when false -> true | _ -> false` is false, implying that `when` applies to the whole `2 | 1`:

```fs
        match x.Length with
        | 1 when x.Span.[0] |> System.Char.IsSurrogate |> not ->
        | 2 when x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate ->
            x |> UnicodeCharacter |> ValueSome
        | _ -> ValueNone
```
If `|` is after `->`, then the two patterns are combined.

## Pros and Cons 

The advantages of making this adjustment to F# are more conciseness, less typing, less cognitive load!

The disadvantage of making this adjustment to F# is that as with any syntax change, we might be making F# more complex.

## Alternative proposal

I propose that the current when condition should be handled as a full-blown pattern like & and |, in the sense that they can be parenthesized. It will be called a "when pattern" in the sense that it can be inserted wherever a pattern can be accepted. Just like the current when condition, any completeness checking is automatically lost.

The example above would be written as:

```fs
        match x.Length with
        | (1 when x.Span.[0] |> System.Char.IsSurrogate |> not)
        | (2 when x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate) ->
            x |> UnicodeCharacter |> ValueSome
        | _ -> ValueNone
```

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: Couldn't find any, please point it if any

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by jindraivanek** [comment] 2019-01-21 07:34
### Current state

`when` guard can be used only for whole "subpattern" (before `->`). For details see:

https://fsharp.org/specs/language-spec/4.1/FSharpSpec-4.1-latest.pdf#page=115&zoom=auto,-82,755

### Workaround

We can create `When` active pattern:

```
let (|When|_|) p _ = if p then Some () else None
```

Your example can be then written as:

```
match x.Length with
    | 1 & When (x.Span.[0] |> System.Char.IsSurrogate |> not)
    | 2 & When (x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate) ->
        x |> UnicodeCharacter |> ValueSome
    | _ -> ValueNone
```

**Comment by jindraivanek** [comment] 2019-01-21 16:45
@theprash Thanks for pointing that out, wasn't aware that infix operators didn't work in patterns. Looks like also other things don't work, like lambdas or indexing. Basically only function calls and other patterns are allowed. I don't see why any expression shoudln't be allowed, because you can do it by calling custom function. Agree it would be good addition.

So, my workaround is not helping much here.

**Comment by glchapman** [comment] 2019-03-04 17:05
Another possibility might be to extend array pattern syntax to System.Memory. If that were possible, you could do something like;
```
let |Surrogate|_| c = if System.Char.IsSurrogate c then Some () else None
// etc for other Char tests -- would be nice to be able to use ValueOption here

let Create (x: chars) =
    match x with
    | [| Surrogate |] -> ValueNone
    | [| _ |]
    | [| HighSurrogate; LowSurrogate |] ->
        ValueSome (UnicodeCharacter x)
    | _ -> ValueNone
```

**Comment by codingedgar** [comment] 2020-08-26 22:44
I think this would be confusing with the classic [switch statements](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch#the-switch-section) with two sections combined:

```csharp
      switch (caseSwitch)
      {
          case 1:
              break;
          case 2:
          case 3:
             // ^^^^ like these
             break;
          default:
              break;
      }
```

In the case of C# a switch section can have multiple labels (case 2, case 3).


On another note, I think that example could be rewritten as a huge clause and you could accomplish what you want, being the clause so big, maybe doing another fun with the actual logic. 

```fsharp
    let Create (x:chars) =
        match x with
        | y when (y.Length = 1 && y.Span.[0] |> System.Char.IsSurrogate |> not)
                   || y.Length = 2 && y.Span.[0] |> System.Char.IsHighSurrogate && y.Span.[1] |> System.Char.IsLowSurrogate ->
            y |> UnicodeCharacter |> ValueSome
        | _ -> ValueNone
```

Or if all the control flow can only be placed at runtime, then why pattern you could question pattern at all:

```fsharp
    let Create (x:chars) =
        if ((x.Length = 1 && x.Span.[0] |> System.Char.IsSurrogate |> not)
                   || (y.Length = 2 && x.Span.[0] |> System.Char.IsHighSurrogate && y.Span.[1] |> System.Char.IsLowSurrogate))
        then x |> UnicodeCharacter |> ValueSome
        else ValueNone
```

However, if notice, you're not pattering much on `x.Length` but if what if we pattern on the result of the clause instead??

```fsharp
    let Create (x:chars) =
        match (x.Length,
                    (x.Span.[0]
                     |> System.Char.IsSurrogate),
                    (x.Span.[0]
                     |> System.Char.IsHighSurrogate 
                             && x.Span.[1]
                                   |> System.Char.IsLowSurrogate)) with
        | (1, false, _) -> Some x 
        | (2, _, true) -> Some x
        | _ -> None
        |> Option.fold(fun _ x -> x |> UnicodeCharacter |> ValueSome) ValueNone 
```

Could think of this as matching the clauses instead of the structure, tho I guess the original case could also benefit from `Option.fold`, that way you're not repeating anything.

**Comment by codingedgar** [comment] 2020-08-27 01:12
> maybe doing another fun with the actual logic

Sorry I never expanded on this:

```fsharp
    let isValid (x:chars) =
        match x.Length with
        | 1 when x.Span.[0] |> System.Char.IsSurrogate |> not -> true
        | 2 when x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate -> true
        | _ -> false

    let isValid (x:chars) =
        match x with
        | x when x |> isValid -> x |> UnicodeCharacter |> ValueSome
        | _ -> ValueNone

```

**Comment by codingedgar** [comment] 2020-08-27 02:17
# If I think this is a "convergence" side of the match expression #

Match expressions are defined as a tool for branching control, but more often than not I do convergence rather than divergence on them.

If the proposal worked where I've been using the "chooser" (`chooser : 'T -> 'U option`) strategy (idk how to call it, but I was inspired by [List.choose](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#choose)) I'll be just, not doing anything 🎉.

Entertaining the idea a bit, I think the main point is where to put it?

Let's see the match expression Syntax for a second: 

```fsharp
// Match expression.
match test-expression with
| pattern1 [ when condition ] -> result-expression1
| pattern2 [ when condition ] -> result-expression2
| ...
```

Every branch seems to have 4 elements: `|`, "pattern", `when`, and the "result expression".

## What about in the beginning? `|` ##

What if we change the `|` symbol?

```fsharp
// Match expression.
match test-expression with
|| pattern1 [ when condition ]
|| pattern2 [ when condition ] -> result-expression2
| ...
```

If we do this, maybe it is understandable that `|` is interpreted as an "if", and `||` as "or" and maybe `&&` as and, and other stuff could be added there, generalizing:

```fsharp
// Match expression.
match test-expression with
branch-operator pattern1 [ when condition ]
branch-operator pattern2 [ when condition ] -> result-expression2
branch-operator ...
```

So we could add this `branch-operator` to the syntax?? and it would be very easy to see and maybe extend, I cannot see any syntax issue analyzing it on its own.

Analyzing it in conjunction with the rest of the expression I do, however, find problems with it

### Bindings ###

Even if the "or branch operator" is a thing or the syntax is just as the original (just omitting the result-expression) I'm left with one issue, bindings.

If we use patterns that decompose data into constituent parts and bind them (destructuring) or we use an `as Pattern`, then what about name conflicts and scope?

Different than C# switch statement where the case is evaluated and the scope is not related to the label, in the case of match expressions, it is.

```fsharp
type MyRecord = { Name: string; ID: int }

let IsMatchByName record1 (name: string) =
    match record1 with
    || { MyRecord.Name = nameFound;} ->
    || { MyRecord.ID = id; } -> nameFound = name // but name is not in both branches!
    | _ -> false
```

This way I conclude if this exists it has to be on the same branch expression or force both branches to be completely compatible regarding bindings.

## In the `when` ##

As the `when` condition it's only evaluated on run time, then I'd say this is referred to the area of runtime control flow (if/then/else/etc), which is where my previous examples elaborated.

## In the result expression (right of `->`) ##

In the case of `let x = y` the [verbose syntax](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/verbose-syntax) is `let x = y in` but this doesn't conflict with indentation, or anything else. If I take the other examples of lightweight vs verbose syntax, all they do is remove "obvious" keywords inferable by indentation.

If I say this proposal seems like a "Lightweight syntax" (sort of speak) of pattern matching, then how would the Verbose syntax look like?

```fsharp
match x with
| y when c1 -> 
   match y when c1 || c2 -> 
   | z -> ...
```

This doesn't seem very primitive to me, neither generalized, because now the proposals would be, can `||` be `f` so it is valid for more options? (like `and`)

Also, doesn't this defeat the purpose of the pattern and the guard clause?

## In the pattern ##

### wildcard ###
Match expressions have wildcards (`_`), which are a form of convergence, but it's not useful in our use case.

### the OR patter, the AND pattern, and the Parentherized Pattern ###

There is the [OR pattern](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#or-pattern):

> The OR pattern is used when input data can match multiple patterns, and you want to execute the same code as a result. The types of both sides of the OR pattern must be compatible.

```fsharp
let detectZeroOR point =
    match point with
    | (0, 0) | (0, _) | (_, 0) -> printfn "Zero found."
    | _ -> printfn "Both nonzero."
detectZeroOR (0, 0)
detectZeroOR (1, 0)
detectZeroOR (0, 10)
detectZeroOR (10, 15)
```

The [AND pattern](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#and-pattern):

>The AND pattern requires that the input match two patterns. The types of both sides of the AND pattern must be compatible.

>The following example is like detectZeroTuple shown in the Tuple Pattern section later in this topic, but here both var1 and var2 are obtained as values by using the AND pattern.

```fsharp
let detectZeroAND point =
    match point with
    | (0, 0) -> printfn "Both values zero."
    | (var1, var2) & (0, _) -> printfn "First value is 0 in (%d, %d)" var1 var2
    | (var1, var2)  & (_, 0) -> printfn "Second value is 0 in (%d, %d)" var1 var2
    | _ -> printfn "Both nonzero."
detectZeroAND (0, 0)
detectZeroAND (1, 0)
detectZeroAND (0, 10)
detectZeroAND (10, 15)
```

and the [Parenthesized pattern](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/pattern-matching#parenthesized-pattern):

>Parentheses can be grouped around patterns to achieve the desired associativity. In the following example, parentheses are used to control associativity between an AND pattern and a cons pattern.

```fsharp
Copy
let countValues list value =
    let rec checkList list acc =
       match list with
       | (elem1 & head) :: tail when elem1 = value -> checkList tail (acc + 1)
       | head :: tail -> checkList tail acc
       | [] -> acc
    checkList list 0

let result = countValues [ for x in -10..10 -> x*x - 4 ] 0
printfn "%d" result
```

Not gonna lie, these are new to me, and it looks like they cheek all the boxes, found then just before clicking "comment", and they look like what we have wanted all along, but better.

a rewrite of the use case:

```fsharp
  let Create (x: chars) =
    match x.Length,
          x.Span.[0]
          |> System.Char.IsSurrogate
          |> not,
          x.Span.[0]
          |> System.Char.IsHighSurrogate
          && x.Span.[1] |> System.Char.IsLowSurrogate with
    | (1, false, _)
    | (2, _, true) ->
        x
        |> UnicodeCharacter
        |> ValueSome
    | _ -> ValueNone
```

this is completely valid syntax and is darn close to the proposal, just take the `when` out of the picture because the "or" is the pattern.

F# is great, just waisted like 3h trying to invent something that's already there 😂, guess there's no proposal to be made.

**Comment by Happypig375** [comment] 2020-08-27 08:36
>a rewrite of the use case:
>
>```fs
>  let Create (x: chars) =
>    match x.Length,
>          x.Span.[0]
>          |> System.Char.IsSurrogate
>          |> not,
>          x.Span.[0]
>          |> System.Char.IsHighSurrogate
>          && x.Span.[1] |> System.Char.IsLowSurrogate with
>    | (1, false, _)
>    | (2, _, true) ->
>        x
>        |> UnicodeCharacter
>        |> ValueSome
>    | _ -> ValueNone
>```
Except that indexing is done before checking Count and an empty Span will throw `IndexOutOfRangeException`.

**Comment by codingedgar** [comment] 2020-08-27 15:49
> Except that indexing is done before checking Length and an empty Span will throw `IndexOutOfRangeException`.

Right, then those runtime checks should be runtime checked in a function, there's no structural pattern to be matched.

### Expanding ###

If two (full) cases (with `when` included) pointed to the same result expression, then not only both patterns should be compatible (as required by the or expression, due binding) but both guards too, otherwise if the `length = 1` case matched and you try to access `.[1]` you'll also have a runtime exemption.

If both guards need to be compatible, then that's an AND, not an OR, and if it is an AND, then the reduction would be just one function guard, going back to the already existing patterns or to a normal function, there's no discrimination of cases.

If two cases could point to the same result expression (an OR in the guard), meaning if the patterns (static) and guards (dynamic) guarantees differ, then there's no case guarantee at all for the result expression, rendering pattern match useless.

The match expression makes sense because there's something to discriminate about, either structurally or dynamically, if not, then it's no branch control at all.

### Back to the use case ###

In one branch you need the guarantee you can access `.[0]` and in the other, you need the guarantee you can access `.[1]` but the `create` function just cares if either is true.

One sense full way to express that explicit intent is:

```fsharp
    let Create (x:chars) =
        
        if (match x.Length with
            | 1 -> x.Span.[0] |> System.Char.IsSurrogate |> not
            | 2 -> x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate 
            | _ -> false)
        then x |> UnicodeCharacter |> ValueSome
        else ValueNone
```

This is one way I see the match expression used as intended: providing guarantees to each branch with the purpose of avoiding runtime exceptions.

Can't think of a way the proposal makes more sense that the snippet above, sorry.

Either way, thank you, never thought about how well designed the match expression was until now.

**Comment by cartermp** [comment] 2020-08-27 16:09
FWIW this would be the alternatives I would write:

```fsharp
module UnicodeCharacter =
    let Create' (x:chars) =
        if x.Length = 1 && x.Span.[0] |> System.Char.IsSurrogate |> not then
            x |> UnicodeCharacter |> ValueSome
        elif x.Length = 2 && x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate then
            x |> UnicodeCharacter |> ValueSome
        else
            ValueNone
               
    let Create (x:chars) =
        match x.Length with
        | 1 when x.Span.[0] |> System.Char.IsSurrogate |> not ->
            x |> UnicodeCharacter |> ValueSome
        | 2 when x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate ->
            x |> UnicodeCharacter |> ValueSome
        | _ -> ValueNone
```

I wouldn't write code that combines the two cases inside of a single `if` check, that kind of boolean logic is just too tricky to follow. In the end this only saves a single line. I suppose it could save N-1 lines for N possible tests, and is far more attractive than combining everything into a single giant condition test in an `if`.

Barring any unexpected limitations in the language I'd say this is reasonable.

> The disadvantage of making this adjustment to F# is that as with any syntax change, we might be making F# more complex.

I would also say that a disadvantage here is that it offers another way to do the same thing with an `if`, though that existing way kind of sucks.

**Comment by abelbraaksma** [comment] 2020-08-27 17:27
I like to think this is a reasonable addition, but the tricky bit will be to come up with unambiguous rules:

How do we decide which branches the `when` clauses apply to if they're mixed (some with, some without under one target expr)? I imagine all the previous ones that don't have a `when` clause? Are they thus grouped?

There's also the issue of what's in focus under the `when`, as the current rules (all under the same target expr must have the same var bindings) wouldn't apply anymore.

**Comment by Happypig375** [comment] 2020-08-27 18:21
@abelbraaksma Can we treat it as if the branch result is copied to each branch with `-> |`?

**Comment by abelbraaksma** [comment] 2020-08-28 14:29
Ok, let's see if we can get concrete here. Let's define some rules:

### Definitions:

**(a)** A _pattern block_ is a combination of top level `AND` and `OR` patterns, before a function arrow `->`.
**(b)** A _pattern rule_ is a single `AND` or `OR` pattern, may be parenthesized
**(c)** A _when condition_ is a `when`-clause
**(d)** A _target expression_ is the expression following the function arrow `->` in a match expression.
**(e)** A _compound when condition_ is a _pattern block_ with multiple _when conditions_.

### New rules for compound `when` conditions

1. A _pattern block_ can have multiple _when conditions_, at most one for each _pattern rule_.
2. Each _when condition_ applies to all _pattern rules_ prior to that _when condition_, up until, but not including, a previous _pattern rule_ in the same _pattern block_.
3. A _when condition_ can never span multiple _pattern blocks_.
4. A _when conditon_ applies to at least one, or more _pattern rules_.
5. There is no requirement that the last _pattern rule_ in a _pattern block_ must have a _when condition_, in absence thereof, it can be implied as `when true`.
6. A _target expression_ is true if and only if all _when conditions_ contained in the corresponding _pattern block_ are true.
7. The set of bound variables in a _compound when expression_ follows the same rules as current rules for a single _when condition_, that is, for each `OR` expressions in the _pattern block_ they must be equal, for `AND` expressions, capturing is combined.

### Ways of expansion

For a given expression like:

```f#
match x with
| A when W_A
| B 
| C 
| D when W_B
| E -> doSomething()
```

This can be viewed as if writing:

```f#
match x with
| A when W_A && W_B -> doSomething()
| B 
| C 
| D when W_A && W_B -> doSomething()
| E when W_A && W_B -> doSomething()
```

Of course, ideally the compiler would write this more like:

```f#
match x with
| A
| B 
| C 
| D
| E -> if W_A && W_B then doSomething() else nextMatch()
```

This is all just a sketch of your idea, and I hope I understood it correctly. Undoubtedly this isn't going to be easy to implement, considering how complex matching internals already are, and the capturing of variables is a thing to consider as well.

**Comment by Happypig375** [comment] 2020-08-28 14:55
>For a given expression like:
>
>```fs
>match x with
>| A when W_A
>| B 
>| C 
>| D when W_D
>| E -> doSomething()
>```
>This can be viewed as if writing:
>```fs
>match x with
>| A when W_A && W_D -> doSomething()
>| B 
>| C 
>| D when W_A && W_D -> doSomething()
>| E when W_A && W_D -> doSomething()
>```

As mentioned in the original post, the current precendence is `|` before `when`, so an expression like
```fs
match x with
| B 
| C 
| D when W_D -> doSomething()
```
will result in `match x with (B | C | D) when W_D -> doSomething()`. This compatibility must be preserved.

**Comment by Happypig375** [comment] 2020-08-28 14:57
What I mean is for
```fs
        match x.Length with
        | 1 when x.Span.[0] |> System.Char.IsSurrogate |> not ->
        | 2 when x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate ->
            x |> UnicodeCharacter |> ValueSome
        | _ -> ValueNone
```
to expand to
```fs
        match x.Length with
        | 1 when x.Span.[0] |> System.Char.IsSurrogate |> not ->
            x |> UnicodeCharacter |> ValueSome
        | 2 when x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate ->
            x |> UnicodeCharacter |> ValueSome
        | _ -> ValueNone
```
, i.e. the branch result is copied to previous branches without results.

**Comment by abelbraaksma** [comment] 2020-08-28 15:08
> will result in match x with (B | C | D) when W_D -> doSomething(). This compatibility must be preserved.

Exactly, and that's precisely what I described. It's in rule \#2:

> Each when condition applies to all pattern rules prior to that when condition, up until, but not including, a previous pattern rule in the same pattern block.

and the example shows how it would expand if the new situations is encountered where there are multiple _when conditions_ inside a single _pattern block_.

**Comment by Happypig375** [comment] 2020-08-28 15:44
I think these two do different things:
>For a given expression like:
>
>```fs
>match x with
>| A when W_A // A when W_A
>| B 
>| C 
>| D when W_D // B|C|D when W_D
>| E -> doSomething() // E when true
>```
>This can be viewed as if writing:
>```fs
>match x with
>| A when W_A && W_D -> doSomething() // A when W_A && W_D
>| B 
>| C 
>| D when W_A && W_D -> doSomething() // B|C|D when W_A && W_D
>| E when W_A && W_D -> doSomething() // E when W_A && W_D
>```

**Comment by Happypig375** [comment] 2020-08-28 15:47
I intend for
```fs
match x with
| A when Z ->
| B
| C when Y ->
| D ->
| E when X -> doSomething()
```
to mean
```fs
match x with
| A when Z -> doSomething()
| B
| C when Y -> doSomething()
| D -> doSomething()
| E when X -> doSomething()

**Comment by abelbraaksma** [comment] 2020-08-28 16:03
Ah, I now understand the difference, thanks. I'll give it another go, though I don't think your simplification holds in all cases, given the possibility of `AND` expressions (actually, mine doesn't either).

**Comment by abelbraaksma** [comment] 2020-08-28 16:20
Let's add one more example, because I got myself confused in thinking we could allowed `when` on an `&`-pattern, but that's not the proposal here. I think this is what's within the scope:

```f#
let f a b =
    match a with
    | None                          // disallowed
        & Some x                      // extra 'when' allowed
    | Some x when x = b -> 1        // 'when' currently allowed
    | Some 42                       // extra 'when' allowed
    | Some 43                       // extra 'when' allowed
    | Some 44                       // extra 'when' allowed
    | Some 45                       // extra 'when' allowed
    | None when b > 2 -> 2          // 'when' currently allowed
    | Some 2                        // disallowed
        & Some x when x < b -> x      // 'when' currently allowed
    | (Some 3 | Some 4 | Some 5)    // disallowed
        & (Some 6 | Some 7)           // disallowed
        & Some x                      // extra 'when' allowed
    | Some 3                        // disallowed
        & (Some x | Some x & None)    // extra 'when' allowed (but not inside parens)
    | Some 4                        // disallowed
        & Some x                      // disallowed
        & (Some 5 | None) when x > b -> 4     // 'when' currently allowed
```

**Comment by codingedgar** [comment] 2020-08-28 20:16
> ```fsharp
> match x with
> | A when Z -> doSomething()
> | B
> | C when Y -> doSomething()
> | D -> doSomething()
> | E when X -> doSomething()
> ```

Then `doSomething()`, cannot scope the bindings or guarantees (guards) of neither branch, I mean, It cannot be sure if `A` or `Z` or `C` or `Y` or `E` or `X` happened because either could have happened.

This is impossible: 

```fsharp
match x with
| A as a when Z ->
| B
| C as c when Y ->
| D as d ->
| E as e when X -> 
   e.count + 1 // this is not possible, because: what if A branch was matched? Also, you have 0 guarantees `when Z` passed.
```

This would have no problems if the result expression wasn't scoped to the branch pattern or didn't care for the guards.

If the result expression cannot scope the pattern bindings or be sure if the condition was matched it is literally the behavior of a C# switch case.

```fsharp
match x.Length with
        | 1 ->
        | 2 -> 
           x.Span.[1] // <- this should pass in `| 2` branch but will throw in `| 1`, this is what I mean.
        | _ -> false
```

Can you explain what would be the benefit of allowing that expression to be valid?

In other thought, if branches could be "or'ed", meaning both bring the exact same guarantees to the result expressions, then there will be no problem to "OR"  the branches, then by algebra, they will be candidates for Absorptive law, and it is possible to write them in a single branch.

Sorry, **I like the idea**, I just seriously cannot see how it would work.

**Comment by abelbraaksma** [comment] 2020-08-28 22:25
> Then doSomething(), cannot scope the bindings or guarantees (guards) of neither branch, I mean, It cannot be sure if A or Z or C or Y or E or X happened because either could have happened.

@codingedgar  Bindings would work the same way it does now, all or expressions must bind the same. It's essentially a different way of writing the same in large, more convoluted `if` statement. You can already do this, except for writing multiple `when`, where each is tied to the current `|` branch.

Look at it another way: it's like using `&` patterns, but with the full power of a `when` clause. Just like with `&` patterns, the bindings are irrelevant,as they're already required to be bound in the enclosing `|` pattern.

**Comment by codingedgar** [comment] 2020-08-28 22:59
@abelbraaksma I already wrote extensively about that above tho, but got no answer from OP.

A syntax for a valid `case | case -> result expression`, by all reductions ends up being an `if then else` expression.

**Comment by abelbraaksma** [comment] 2020-08-28 23:45
So, then we agree it's a simpler syntax, or at least an alternative, for a match + complex if expression, just line @cartermp summarized above as well. 

I think it has merit when you have many DU cases, and some need to be grouped on conditions. I've wanted to write this a few times myself, only to be called back by the compiler.

As suggested, I believe it fits orthogonally in the language.

**Comment by codingedgar** [comment] 2020-08-29 00:40
Yeah me too, I just think the match expression isn't the place to put it, maybe a new expression?

This is like `allPass`, `anyPass` don't you think? Same as C# switch case with sections, those discard the scope of the case (bindings) and just care it passes. `anyPass` is pretty much what we want I think.

**Comment by abelbraaksma** [comment] 2020-08-29 01:09
I don't think there's a problem to meaningfully parse this, it'll be just (ebnf simplified) `| patexpr [& patexpr]* [when expr]?]? "->" expr` for each `OR` pattern. Then no extra syntax is needed.

**Comment by Happypig375** [comment] 2020-08-29 03:25
Alternatively, we can also allow `when` to be a pattern, such that
```fs
match x with
| (A when Z)
| (B | C when Y)
| D
| E when X -> doSomething()
```
is equivalent to
```fs
let (|InlinePat1|_|) x = if Z then Some() else None
let (|InlinePat2|_|) x = if Y then Some() else None
let (|InlinePat3|_|) x = if X then Some() else None
match x with
| A & InlinePat1
| (B | C) & InlinePat2
| D
| E & InlinePat3 -> doSomething ()
```
.

**Comment by abelbraaksma** [comment] 2020-08-29 09:41
@Happypig375, that last suggestion doesn't seem like an improvement to me, as that's already possible with `&`. Besides, changing `when` to take a pattern would lead to backward compat issues.

No, I'd stick to your original suggestion: allow `when` on each top level `|` branch. No compat issues, and more expressive freedom.

**Comment by Happypig375** [comment] 2020-08-29 09:49
> that last suggestion doesn't seem like an improvement to me, as that's already possible with `&`.

`when`s are more free-form than `&`: https://github.com/fsharp/fslang-suggestions/issues/715#issuecomment-456019998
Besides, why write active patterns for each and every `when` clause that are only used one time when the compiler can do that for you?
Also, unlike my original proposal, we can parenthesize `when`s together:
```fs
match x.Length with
| (1 when x.Span.[0] |> System.Char.IsSurrogate |> not)
| (2 when x.Span.[0] |> System.Char.IsHighSurrogate && x.Span.[1] |> System.Char.IsLowSurrogate) ->
    x |> UnicodeCharacter |> ValueSome
| _ -> ValueNone
```
which allow for more places for them to be used as they can now be written as nested patterns.
> Besides, changing `when` to take a pattern would lead to backward compat issues.

No, `when`s will keep their current precendence - below the OR pattern. That's why they are parenthesized.

**Comment by abelbraaksma** [comment] 2020-08-29 10:05
But you said in your penultimate post that you wanted to let `when` take a pattern? Currently it takes an expression that returns bool. I think changing that is problematic. 

If that's not what you meant, I don't understand. Perhaps you were talking about how the compiler could interpret this internally? We shouldn't really be too concerned about how the compiler optimizes things, but instead try to create a syntax that can be parsed unambiguously. Your original proposal has that.

**Comment by Happypig375** [comment] 2020-08-29 10:27
I propose that the current `when` condition should be handled as a full-blown pattern like `&` and `|`, in the sense that they can be parenthesized. It will be called a "when pattern" in the sense that it can be inserted wherever a pattern can be accepted. Just like the current `when` condition, any completeness checking is automatically lost.

**Comment by abelbraaksma** [comment] 2020-08-29 11:16
Ah, you're proposing something new ;). It's probably better to do that in a new suggestion, as it's diverging a lot from this one, which was already half way accepted by @cartermp.

**Comment by Happypig375** [comment] 2020-08-29 12:23
This is an alternative to this proposal though. The template even encourages alternate proposals.

**Comment by abelbraaksma** [comment] 2020-08-29 21:38
Yes, in the template. Well, it's your suggestion, in my experience, if you want to track such alternatives, people won't go through dozens of comments, so it's either keeping track of them by editing the original suggestion, or raising a new one, if you want visitors to notice them. 

The template for the dotnet runtime does a better job in explaining this. Maybe we should update it for F#. 

But of course, in the end it's up to you how you want to drive this ;).

**Comment by Happypig375** [comment] 2020-08-30 05:34
Edited

**Comment by dsyme** [comment] 2023-04-12 14:42
I'm not in favour of making additions/changes around `when` in pattern matching. 

The situation today is stable and well-documented.  It causes some confusion as `when` applies over an entire set of disjunctive matches, but that is fairly well known.  

I think adding further things in this area won't be productive in balance

**Closed by dsyme** 2023-04-12 14:42 UTC
Labels: area: pattern-matching
