### ISSUE TITLE
Implement OCaml's new match/exception syntax

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#340] opened 2016-10-20 02:49 UTC
**Submitted by Eirik George Tsarpalis on 10/8/2014 12:00:00 AM**  
**42 votes on UserVoice prior to migration**  

Implement the feature that is nicely described in the following post:
https://blogs.janestreet.com/pattern-matching-and-exception-handling-unite/

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6536829)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6536829-implement-ocaml-s-new-match-exception-syntax.md#comments)

**Comment by dsyme** [comment] 2016-10-29 18:03
While I like this suggestion, realistically I don't think we'll be adding this to F#. Mainly because of the general cost/churn involved in doing so.

**Comment by Alxandr** [comment] 2016-11-16 15:50
Wait, this issue has a high cost? It seems really straight forward to me. What are the issues? As far as I can see the problem would consists of the following steps:

1. Modify parser to enable `"exception" <ExceptionPattern>` in switch clauses.
2. In cases where a switch has one or more exception clauses, extract the exception clauses and emit them as a try-catch.

Now, I'm no expert on these things, and have worked little with the F# compiler, so the likelihood that I've overlooked something is not low, I'm just looking to understand why this issue is considered costly. To me this seems like a fairly easy to implement quality of life improvement.

**Comment by cartermp** [comment] 2016-11-16 22:11
I can't speak towards the implementation (although I suspect this would involve significant code churn in the IL emitted by a `match` expression which could also support exceptions), but it also creates a bit of a problem in terms of having multiple ways to do the same thing.  Assuming we had an implementation on hand, I see major problems:

1. Are `finally` semantics a consideration?  How would that look?
2. Creating a rift between the "old" way of exceptions and the "new" way of exceptions.

I like the idea that exceptions can also be thought of as patterns - the "shape" of the result could be an exception that one needs to handle, if the compiler could potentially be smart enough to recognize that and force you to account for those exceptions.  However, that's also going down the checked exceptions path, and that's problematic because (a) most people hate checked exceptions, and (b) most "solutions" to dealing with checked exceptions is to either re-throw and let something else deal with the problem, or a Pokemon-style "Gotta catch 'em all!" approach by simply handling the `Exception` case and calling it a day.

Even if the implementation were simple, I think there would need to be a pretty detailed spec on how exception-handling for F# needs to look like in the future, and why that's better than what we currently have.  Lots of unanswered questions.

**Comment by Alxandr** [comment] 2016-11-17 08:38
First of all, with regards to finally, last I checked F# already forces you to split that up. So if you want try-catch-finally, you have to write it like this:

```fsharp
try
  try
    DoStuff()
  with
  | ?: MyExn -> DoOtherStuff()
finally
  CleanUpStuff()
```

What I'm thinking is that match expressions with exception clauses could be implemented as a simple AST transform without needing any change to IL emitting. Basically you take the AST of this:

```fsharp
match DoStuff() with
| 5 -> "success"
| exception ?: MyExn -> "failure"
```

and you convert it into

```fsharp
try
  match DoStuff() with
  | 5 -> "success"
with
| ?: MyExn -> "failure"
```

The only issue I see with this is dealing with match exceptions (if `DoStuff()` doesn't return 5 and doesn't throw, I would not expect it to be catchable in the match expression).

**Comment by cartermp** [comment] 2016-11-18 00:15
@Alxandr right, there is a split on `finally` vs not already, but my question was about what, if any, consideration there would be for this.  As you've described it, this introduces a third way to handle exceptions, rather than a successor to the current `try...with` and `try...finally` split.

Your proposal, to have this essentially just be syntactic sugar for a `match...with` enclosed in a `try..with`, I think violates the principle of least surprise.  My first reaction to seeing an exception as a pattern in a `match...with` expression is to think that the exception is a return value rather than a true exception.  This also makes type checking strange - if the return value of `DoStuff()` is a DU and I want the compiler to enforce all possible cases, then the exception case isn't counted because it's *actually* a `try...with` wrapping the pattern match.  That isn't very straightforward to me.

> The only issue I see with this is dealing with match exceptions (if `DoStuff()` doesn't return 5 and doesn't throw, I would not expect it to be catchable in the match expression).

If I'm interpreting this correctly, you're suggesting that doing something like this:

```fsharp
match DoStuff() with
| 5 -> "success"
| exception ?: MyExn -> "failure"
```

would be a compiler error if `DoStuff()` doesn't throw an exception anywhere in its code paths?  If so, I believe that could be quite a bit of work to get right, especially if we consider tracing functions which `DoStuff()` calls (or could call).

**Comment by radekm** [comment] 2016-11-18 06:33
> What I'm thinking is that match expressions with exception clauses could be implemented as a simple AST transform without needing any change to IL emitting.

But then you'll lose tail call optimization which is one of the main benefits of this construction in OCaml.

**Comment by Alxandr** [comment] 2016-11-18 10:58
@cartermp You've misinterpreted what I said about match exceptions. To illustrate in code:

```fsharp
try
  match 3 with
  | 5 -> "success"
  | exception ?: MatchFailureException -> "inner error"
with
| ?: MatchFailureException -> "outer error"
```

I would expect the output of the following code to be "outer error", and not "inner error", because the `MatchFailureException` is thrown by the match statement itself, rather than what I'm matching. If however, we move back to `DoStuff()` example, and `DoStuff()` threw a `MatchFailureException`, I would expect "inner error".

@radekm You're right. I didn't read that much of the blog post explaining the OCaml construct. However, the same post explains how swapping the order of the match and the try resolves this problem, so what you could perceivably do is something like this:

```fsharp
// original
match DoStuff() with
| 5 -> "success"
| exception ?: MyExn -> "failure"

// transformed (pseudo-syntax in some cases)
type MatchExceptionResult<'a> =
| Success of 'a
| Exn of exn

match (try DoStuff() |> Success with | e -> Exn e) with
| Success(5) -> "success"
| Exn(?: MyExn) -> "failure"
| Exn(e) -> raise e
```

By having the invented `MatchExceptionResult` type be a structure, you would have zero allocations, and you would still be tail-recursive. I also solved my problem with `MatchFailureException` inadvertently, so that's always a bonus.

Now, I'm not saying this is *the* solution, I'm just saying I like this suggestion, and would like a discussion as to why it's considered costly, because to me this seems like a real boon. Especially if it makes things more tail recursive.

**Comment by cartermp** [comment] 2016-11-18 14:09
@Alxandr Makes sense!  I think that's very reasonable behavior.

I still think that reasonable behavior when typechecking needs to be hashed out, and I'm still leery of introducing another way to handle exceptions.  I suppose an option to also support `finally` is to have it expand like your suggestion, from:

```fsharp
match DoStuff() with
| 5 -> "success"
| exception ?: MyExn -> "failure"
| finally -> "wwhheee"
```

to something along the lines of:

```fsharp
try
    try
        match DoStuff() with
        | 5 -> "success"
     with
      | exception ?: MyExn -> "failure"
finally
    printfn "Always print this."
```

But I'm not quite sure that's the right thing to do, since it introduces an imperative construct into something which is expression-based, and would require quite a bit of thought to figure out what the correct behavior of the return type would be.  I think a large part of my hesitance to support this (even though I like the notion of `match` being an even more powerful general-purpose construct), is that exception handling tends to go two ways: (1) imperative code, or (2) using exceptions to generate something like an `None`, or even worse, using `;` and a dummy value to satisfy typechecking.

This feature makes the latter case a bit nicer to deal with, but I think the long-term answer here is for libraries, probably including FSharp.Core, to do something like (2) and generate `Result` types from interop with .NET.  At that point, the majority of uses for exceptions would be when you're in an inescapably imperative scenario, and using exception handling as-is wouldn't feel so awkward.  A good solution there would be to unify the `try..with` and `try..finally` blocks into a `try..with..finally` block, where `finally` is optional, similar to how C# and VB do it.

**Comment by Alxandr** [comment] 2016-11-18 15:20
I'm not sure I agree with unifying `try..with` and `try..finally` in F# though, cause as you said one is imperative, whereas the other one is more of an expression. And that is sort of the point here I think. Exception handling in F# is already (sort of at least) pattern matching. You just do `try..with` instead of `match..with`. Also, as pointed out by @radekm, it makes things more likely to be tail-recursive, which is always a boon.

**Comment by cartermp** [comment] 2016-11-18 17:55
> And that is sort of the point here I think. Exception handling in F# is already (sort of at least) pattern matching.

Yes, capturing the different kinds of exceptions which could occur is pattern-matching-like, but the nuance of having to somehow fit a fundamentally imperative construct like exceptions into a functional paradigm often makes for awkward code.  I don't think that being able to have exception clauses in a `match...with` expression solves that problem; it just surfaces it in a different way.  You're still needing to create a return type which matches the non-exceptional code path, or use a `;` hack to log an error and return a dummy value to satisfy the typechecker.

To summarize my reasoning for pushback :

1. Do we think introducing this new way to handle exceptions will act as a replacement for the current way of doing it, or will it just be yet another way to approach the same problem?
2. How would we expect typechecking to work with this?  How much work is there in getting that right?
3. Do we think this improve the current awkwardness in exception handling?  If we believe so, then what is the reasoning in thinking that is the case?
4. If this represents the preferred way to handle exceptions, there will also be work involved to update documentation and proliferate this new way of doing things across blogs and videos.  Are people comfortable with that kind of re-education?
5. Which scenarios use exceptions today, but could use `Result<'TOk, 'TError>` to persist an error in a functional way tomorrow?  Those kinds of scenarios may benefit from this feature, but I would argue they could be suited to using the result type.  Which scenarios remain where having exception cases be part of `match...with` is an obvious win in terms of clarity of intent?

To be clear, I think that it's a cool feature, and I like the idea that you can really `match` on anything.  @radekm's point is also good, and I agree that it's a boon worth taking a look at.

**Comment by Alxandr** [comment] 2016-11-18 23:34
@cartermp personally I can at least see this being very useful when writing "wrappers" around APIs that do throw exceptions instead of return discrete unions, something like:

```fsharp
type NumberParseResult<'a> =
| Number of 'a
| InvalidFormat
| Overflow

let parseInt str =
  match System.Int32.Parse str with
  | num -> Number num
  | exception ?: FormatException -> InvalidFormat
  | exception ?: OverflowException -> Overflow
```

Now, obviously this is a bit of a stupid example, because it could have been just a `try..with`, cause I'm not doing any actual matching on the result of `Parse`, also there is `TryParse` which I'm choosing to ignore, but I've written code similar to this previously for similar APIs where different exceptions meant different useful things. And I've wrapped the match expression inside the `try..with`.

Also, on a side-note, I'm pretty sure if this gets added to the language I'll likely just stop using `try..with` altogether in favour of a single unifying `match..with`.

**Comment by Alxandr** [comment] 2016-11-18 23:36
Also, on another note, that I didn't address, I have never used the semicolon hack (as you call it) when dealing with exceptions in F#. I always try to write my code functionally, and I have never written a catch block that does not return something of the same type as the try block (albeit that has been `None` a good few times).

**Comment by dsyme** [comment] 2018-03-02 18:43
Comments from the language design office hours

> Fundamentally I like the suggestion.  Since this is an informal suggestion, let me share the history: the original version of the design suggestion originates with Andrew Kennedy and Nick Benton in their ground-breaking work on Standard ML for the JVM  (MLj) - the first ML language to venture onto an industry VM.  They wrote it up in JFP I think, in the first few years of the MSR Cambridge lab. So like units of measure I feel a close affinity to the design point and it is basically a good one.
> 
> My only negative comment above was that it would be hard to add, just for syntax reasons alone, and also for a desugaring in computation expressions.  But if those were addressed totally adequately it would be a welcome addition to the language I think. There are plenty of times when it makes sense to use it (though beginners may not discover this)  
> 
> The fact that neither "try" nor "with" occur in the OCaml syntax is a bit distressing from an eductional/code-reading point of view
> 
> I wouldn't put this on my priority list for my own work, but I'll consider marking it approved-in-principle (won't do it yet).  I'll drop these comments in as a note in the suggestion.

**Comment by dsyme** [comment] 2022-06-16 15:35
Now a duplicate of the approved https://github.com/fsharp/fslang-suggestions/issues/895

**Closed by dsyme** 2022-06-16 15:35 UTC
Labels: area: pattern-matching
