### ISSUE TITLE
Add match! (match-bang) syntactic sugar to computation expressions [ RFC FS-1047 ]

### ISSUE THREAD

**Issue by jwosty** [fsharp/fslang-suggestions#572] opened 2017-05-22 16:04 UTC
# Add a `match!` syntactic sugar to computation expressions

When writing computation expressions, especially asyncs that call my own functions returning `Option`s, I find myself quite often binding it (via `let!`), then proceeding to use that variable only one time in a pattern match immediately following. It'd be really nice to eliminate the unnecessary `let!` and have a sort of `match!` that means the same thing as a `let!` followed by a vanilla `match`.

For example, this:

```fsharp
(val myAsyncTryGetResult: 'a -> Async<'a option>)
async {
    let! x = myAsyncTryGetResult foo
    match x with
    | Some(x) -> printfn "got some: %A" x
    | None -> printfn "got none" }
```

could instead be written as:

```fsharp
(val myAsyncTryGetResult: 'a -> Async<'a option>)
async {
    match! myAsyncTryGetResult foo with
    | Some(x) -> printfn "got some: %A" x
    | None -> printfn "got none" }
```

To implement this, the compiler could by default treat it the same as `let!` followed by `match`, <s>or spit out a call to a new builder method for this construct if the builder defines it, perhaps called `BindPattern`. It would be identical in signature to `builder.Bind`.

E.g. compiler could emit

```fsharp
asyncBuilder.Bind(myAsyncTryGetResult foo, (fun x -> match x with ... ))
```
or
```fsharp
asyncBuilder.BindPattern(myAsyncTryGetResult foo, (fun x -> match x with ... ))
```
</s>

## Pros and Cons 

The advantages of making this adjustment to F# are
- Code that encounters this type of annoyance would be a little cleaner
- Non-invasive and simple

The disadvantages of making this adjustment to F# are
- Nonzero effort required :P

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I would be willing to help implement and/or test this
* [] I or my company would be willing to help crowdfund F# Software Foundation members to work on this

**Comment by dsyme** [comment] 2017-05-23 17:43
Looks like a duplicate of this https://github.com/fsharp/fslang-suggestions/issues/316

**Comment by jwosty** [comment] 2017-05-23 23:21
@dsyme looks like you're right, but since Joinads was rejected, could we reconsider? (e.g. reopen the older proposal or keep this one)

**Comment by cartermp** [comment] 2017-05-24 13:53
I think this is a better version of #316 and since Joinads were rejected it could be up for discussion.

@jwosty I'm curious about your views on this vs. writing a different builder, e.g., `asyncMaybe`.  You can accomplish flattening the `match` expression on the result in this way.

**Comment by jwosty** [comment] 2017-05-26 20:56
@cartermp I could see that being useful, but I'd much prefer having `match!`, since it'd cover a lot more cases (e.g. wouldn't be limited to just matching over option types). Using an `asyncMaybe` builder would also require that all the async calls you make inside return an option, which would make it very cumbersome to actually use.

**Comment by rmunn** [comment] 2017-05-29 02:51
In the resolution of https://fslang.uservoice.com/forums/245727-f-language/suggestions/5663965-integrate-joinads-extension it was mentioned that that proposal was being declined "for now". Does that mean that it might be resurrected at some point in the future? If so, it might be wise to hold the `match!` syntax open for some unknown future date when joinads get integrated.

However, if the decision was that joinads would *never* be integrated, then there's no issue with re-evaluating #316 here.

**Comment by ploeh** [comment] 2017-05-29 13:53
@cartermp While one could write a builder for each monad stack one needs, I find myself repeating that `let!/match` idiom over and over again, even in monad stacks (like `asyncMaybe`, or `asyncEither`, etc.).

I often pattern match on domain models, not just on built-in types like `Option` or `Result`. An example could be this [tennis game state](http://blog.ploeh.dk/2016/02/10/types-properties-software-designing-with-types):

```fsharp
type Score =
| Points of PointsData
| Forty of FortyData
| Deuce
| Advantage of Player
| Game of Player
```

As a 'naked' discriminated union, it's not monadic (it's not even a functor), so I'm not sure it's possible to write a computation expression builder for such a type. You might still be able to write one for a combination that involves a proper monad like `async`, but that's a lot of boilerplate code required for each discriminated union.

It's possible that I could write a computation expression builder for e.g. `Async<Score>`, but I haven't tried... Even if possible, I'd also need to write one for `Maybe<Score>`, `Async<Point>`, `Maybe<Point`, and so on. If that's what it takes to avoid writing `let!` followed by `match`, I'll take the `let!/match` combo any time, but a `match!` keyword would be really nice.

**Comment by jwosty** [comment] 2017-05-29 17:52
@rmunn ah, didn't catch that joinads was rejected "for now." Therefore the disadvantage to implementing this suggestion is that it's pretty incompatible, thus if it were implemented, it would prevent Joinads from becoming a thing ever. I wonder if that's possible to avoid somehow (if Joinads is a possibility eventually).

**Comment by jwosty** [comment] 2018-02-28 20:10
Is there anything preventing this from being marked as [approved-in-principle](https://github.com/fsharp/fslang-suggestions/labels/area%3A%20computation-expressions)?

**Comment by realvictorprm** [comment] 2018-03-01 17:49
I'm interested in a statement too. What are the real cons of this? For me it looks like a nice-to-have addition :thinking_face:

**Comment by dsyme** [comment] 2018-03-02 18:24
Marking as approved-in-principle per discussion in language-design office hours

**Comment by boloutaredoubeni** [comment] 2018-03-02 19:16
From language design office hours
> @dsyme Re this:

>> In terms of `bind x || bind y ` and in the context of `async`, would this work similarly to how `Async.Choice` works?

No.  It would just be similar in effect to C# await desugaring (though that has to be more general since `await` is allowed anywhere in the expressions, which is not something I feel we need to do)

`let! part1 = bind x in if part1 then ... else let! part2  = bind y in if part2 then ... else ...
`

The problem of course is that duplicates code (the then... branches), and we'd have to deal with that

**Comment by dsyme** [comment] 2018-03-02 19:17
From Language Design Office Hours:

> John Wostenberg [7:01 PM]
> Happy to see `match!` approved (as seen at https://github.com/fsharp/fslang-suggestions/issues/572)! 
> As for details, any thoughts on the specific implementation of what the compiler would emit?
>
> @dsyme says:
> I'm 100% sure it should simply be short hand for "let! x = y in match x with ..."

**Comment by Rickasaurus** [comment] 2018-03-05 18:26
Oooh man, does this mean we're going to get idris-style inline bind? That would be so rad.

**Comment by jwosty** [comment] 2018-03-05 18:48
@Rickasaurus I'm not familiar with Idris; what's inline bind?

**Comment by jwosty** [comment] 2018-03-05 19:13
Also, after studying joinads a bit more, I think `match!` should allow you to write them as a library add on, using active patterns for example. If anyone's interested, you could explore this and attempt to write one

**Comment by Rickasaurus** [comment] 2018-03-05 20:51
@jwosty this stuff http://docs.idris-lang.org/en/latest/tutorial/interfaces.html#notation

**Comment by jwosty** [comment] 2018-03-05 21:11
@Rickasaurus That's a cool language feature!

**Comment by Rickasaurus** [comment] 2018-03-05 21:14
@jwosty I know right? Idris got it like five years ago and I've been drooling over it ever since.

**Comment by jwosty** [comment] 2018-03-05 21:19
@Rickasaurus  I'm considering opening a feature request for this later

**Comment by dsyme** [comment] 2018-05-29 23:12
Implementation has been submitted

**Closed** 2018-05-29 23:13 UTC
Labels: approved-in-principle, area: computation-expressions, completed

**Comment by et1975** [comment] 2018-09-12 17:41
Just found that `match!` doesn't allow assigning the results, ie:

`let x = match! asyncX with Some v -> v | _ -> failwith "unexpected"`

results in:

> This construct may only be used within computation expressions

and the simplest valid code seems to be:

`let! x =  async { match! asyncX with Some v -> return v | _ -> failwith "unexpected"}`

which is suboptimal. Would it be possible to improve this?

**Comment by cartermp** [comment] 2018-09-12 19:37
I certainly have no objections to allowing assignment of the result. @jwosty, would you have any concerns?

**Comment by dsyme** [comment] 2018-09-17 10:09
> Just found that match! doesn't allow assigning the results, ie:

This is by-design, and nothing to do with `match!`.  The right-hand-side of a `let x = ` is not a computation expression and can't use any computation expression machinery.

**Comment by et1975** [comment] 2018-09-17 20:39
> The right-hand-side of a let x = is not a computation expression and can't use any computation expression machinery.

Right, but the right-hand side of `let!` is, hence the surprise :)

Specifically, in this context: `let! (Some x) = asyncX` match works exactly as expected, but addressing the compiler warning unfurls the right hand side to that... monstrosity.

**Comment by dsyme** [comment] 2018-09-18 10:04
@et1975 Yes, it's somewhat large transition. So 

    let (Some x) = syncX

becomes

    let x = match syncX with Some x -> x | None -> fail() 

and

    let! (Some x) = asyncX

becomes

    let! x = async { match! asyncX with Some x -> return x | None -> fail() }

I suppose we could in theory allow `!` computations on the r.h.s. of a `let` and I don't think it would be a breaking change - just a little odd because the `let` is really a bind.  We should make another issue on that and it would at least be interesting to explore that.

**Comment by bizmonger** [comment] 2019-12-14 12:44
Can we also apply that to the **function** syntax as well?

Example:

 ```
               storageTable
                |> createEntityAsync entity
                |> function!
                   | Error msg -> ...
                   | Ok _ -> ...
```

**Comment by abelbraaksma** [comment] 2019-12-14 16:03
@bizmonger, i believe that was considered, but eventually not included, but I don't remember the reasoning. You should probably open a new language suggestion, a closed one is not likely to be picked up.
