### ISSUE TITLE
Copy-and-update syntax for interfaces (decorator pattern)

### ISSUE THREAD

**Issue by Overlord-Zurg** [fsharp/fslang-suggestions#524] opened 2016-12-08 19:40 UTC
I propose we add syntax to interfaces similar to the copy and update record expression syntax.

Say I want to implement an IList<_> that constrains an existing IList implementation to a maximum item count. Currently I would can do:
```fsharp
let withBound max (list: System.Collections.Generic.IList<'a>) =
    { new System.Collections.Generic.IList<'a> with
        member this.Add(item) =
            if list.Count >= max then failwith "Too many items" else list.Add(item)
        member this.Clear() = list.Clear()
        member this.Contains(item) = list.Contains(item)
        (* ...literally 12 more members *) }
```
With the proposed syntax, I could do:
```fsharp
let withBound max (list: System.Collections.Generic.IList<'a>) =
    { list with
        member this.Add(item) =
            if list.Count >= max then failwith "Too many items" else list.Add(item) }
```
This would make the [decorator pattern](https://dzone.com/articles/is-inheritance-dead) very easy in F#, e.g.:
```fsharp
let myBoundedList =
    List<int>()
    |> withBound 5
```

## Pros and Cons 

The advantages of making this adjustment to F# are ...
- Looks and works almost exactly like the existing syntax for records
- Encourages sound(er) application of OO principles
- Something else to lord over C# until they add it in six to eight years

The disadvantages of making this adjustment to F# are ...
- It's work

## Related Suggestions
* Allow interfaces to be implemented by expressions #132 

## Affadavit (must be submitted)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

**Comment by ReedCopsey** [comment] 2016-12-08 19:52
I would _love_ this, but would still prefer a mechanism to specify the return type (ie: in your example, should it be `IList<'a>`, or `ICollection<'a>`, or ...?)

The ability to return an interface which delegates implementation to another object would be extremely useful, both in object expressions, but also in normal interface implementations, however, I think it'd need different syntax so the interface type was explicit.

Perhaps something like

```fsharp
    { list :> IList<'a> with
        member __.Add item =
            if list.Count >= max then failwith "Too many items" else list.Add(item) }
```

It seems like this could be easier to extend to normal interface definitions:

```fsharp
type Foo<'T> () =
    let internalList = ResizeArray<'T>()

    interface internalList :> IList<'T>
```

And/or:

```fsharp
type Foo<'T> () =
    let internalList = ResizeArray<'T>()

    interface internalList :> IList<'T> with
        member __.Add item =
            () // "override" implementation here
```

**Comment by Overlord-Zurg** [comment] 2016-12-08 20:45
The first expression in the copy-and-update expression would determine the return type, same as record expressions. So, if you wanted to wrap an IList as an IList:
```fsharp
let withBounds x (list: IList<'a>) =
    { list with (...) }
```
If you wanted the result to be a different interface:
```fsharp
let withBounds x (list: IList<'a>) =
    { list :> ICollection<'a> with (...) }
```

I don't think I'm understanding your syntax for the normal interface definitions. With regard to the decorator pattern, it doesn't make sense without passing in an existing instance of the interface, because then you run into the same single-inheritance/fragile-base-class problems that we want to avoid.  I think it would look more like this:
```fsharp
type BoundedList<'a> (list: IList<'a>) =
    list with
        member __.Add(item) = //etc
```
...and then BoundedList<'a> would automatically be marked as implementing the interface of type IList<'a>.

**Comment by matthid** [comment] 2016-12-08 20:58
One addition: It would be even more useful if there is a way to make the underlying field mutable, for example if we could use a `ref`-cell on the first position as well.

But even without that it feels like a logical addition on the first look.

**Comment by ijsgaus** [comment] 2016-12-11 20:12
https://github.com/fsharp/fslang-suggestions/issues/132

**Comment by dsyme** [comment] 2017-03-03 16:07
@matthid 

> One addition: It would be even more useful if there is a way to make the underlying field mutable, for example if we could use a ref-cell on the first position as well.

Could you explain this a bit more please?

**Comment by matthid** [comment] 2017-03-16 23:04
@dsyme Sure. (Sorry for the delay).

Something like (I have no idea how a syntax would look like):

```fsharp
let withBound max (list: System.Collections.Generic.IList<'a>) =
    { mutable list with // I think this should be "marked" somehow, maybe allow a ref cell here?
        member this.Add(item) =
            if list.Count >= max then failwith "Too many items" else list.Add(item) }

let o1 : System.Collections.Generic.IList<'a>= ...
let o2 : System.Collections.Generic.IList<'a>= ...
let wrapper = withBound 3 o1
wrapper.list <- o2 // This
```

Basically a way to "replace" the wrapped object. Otherwise I need to wrap again and then need to implement all members again :). Usually I don't want to replace my code to understand `IList ref` and I would wrap again (making the feature unusable in those situations).

With a ref cell:

```fsharp
let withBound max (list: System.Collections.Generic.IList<'a>) =
    let l = ref list
    { l with // maybe a bit invisible?
        member this.Add(item) =
            if list.Count >= max then failwith "Too many items" else list.Add(item) }, l

let o1 : System.Collections.Generic.IList<'a>= ...
let o2 : System.Collections.Generic.IList<'a>= ...
let wrapper, cell = withBound 3 o1
cell := o2 // This
```

Does that make it clear?

**Comment by matthid** [comment] 2017-03-16 23:15
Maybe 
```fsharp
type Foo<'T> () =
    let mutable internalList = ResizeArray<'T>() // Note the mutable here
    interface internalList :> IList<'T>
```

Would be enough for such situations, more explicit and less special syntax... 
I'd surely love the feature, even without support for mutable :)

**Comment by smoothdeveloper** [comment] 2017-04-26 12:46
Related: https://github.com/dotnet/csharplang/issues/477

**Comment by matthid** [comment] 2019-06-05 22:07
Considering #132 #195 and #555 I think for object expressions the same syntax should be used.
Therefore, I'd suggest:

```fsharp
let withBound max (list: System.Collections.Generic.IList<'a>) =
    { new System.Collections.Generic.IList<'a> by list with
        member this.Add(item) =
            if list.Count >= max then failwith "Too many items" else list.Add(item) }
```

With the same semantics as in https://github.com/fsharp/fslang-suggestions/issues/132#issuecomment-499269331

**Comment by matthid** [comment] 2019-06-05 22:09
Note that regarding [this comment](https://github.com/fsharp/fslang-suggestions/issues/524#issuecomment-287218875) I feel like we should support any expression after `by`, including a ref cell:

```fsharp
let withBound max (list: System.Collections.Generic.IList<'a>) =
    let l = ref list
    { new System.Collections.Generic.IList<'a> by !l with // maybe a bit invisible?
        member this.Add(item) =
            if list.Count >= max then failwith "Too many items" else list.Add(item) }, l

let o1 : System.Collections.Generic.IList<'a>= ...
let o2 : System.Collections.Generic.IList<'a>= ...
let wrapper, cell = withBound 3 o1
cell := o2 // This
```

**Comment by dsyme** [comment] 2021-09-25 11:31
Closing this as a duplicate of #164 , it should all be considered as part of one thing

**Closed by dsyme** 2021-09-25 11:31 UTC
Labels: area: unions-and-records-and-objects

**Comment by Nhowka** [comment] 2023-02-04 00:21
> Note that regarding [this comment](https://github.com/fsharp/fslang-suggestions/issues/524#issuecomment-287218875) I feel like we should support any expression after `by`, including a ref cell:
> 
> ```fsharp
> let withBound max (list: System.Collections.Generic.IList<'a>) =
>     let l = ref list
>     { new System.Collections.Generic.IList<'a> by !l with // maybe a bit invisible?
>         member this.Add(item) =
>             if list.Count >= max then failwith "Too many items" else list.Add(item) }, l
> 
> let o1 : System.Collections.Generic.IList<'a>= ...
> let o2 : System.Collections.Generic.IList<'a>= ...
> let wrapper, cell = withBound 3 o1
> cell := o2 // This
> ```

@dsyme I have a working implementation for the object expression case like this one. The exact code works, only changing the `by` keyword for a simple equals sign. Same as the code on #555, but I couldn't understand how to fit it with #164. Could we revisit that?
