### ISSUE TITLE
remove intrinsic type augmentation deprecation message

### ISSUE THREAD

**Issue by sgtz** [fsharp/fslang-suggestions#691] opened 2018-09-08 22:25 UTC
we get an eviction notice, "warning FS0060: Override implementations in augmentations are now deprecated. Override implementations should be given as part of the initial declaration of a type.", when attempting to use a type module type with

    type SomeType() = 
      member this.SomeMethod() = "hello"

    module SomeType = 
      let helper = id

    type SomeType with
      override this.SomeMethod() = "hello and good morning to you."

I propose we continue to allow this kind of augmentation. modules are a nice home for functions. Blending them together with the type augmentations is (or was) a nice technique.

The existing way of approaching this problem in F# is to continue until this warning gets elevated to an error. Will it get elevated, eventually, or is this merely a style-cop kind of rule that's migrated into the compiler?

## Pros and Cons 

The advantages of making this adjustment to F# are that it's more flexible from a programmers perspective.

The disadvantages of making this adjustment to F# are (guessing), are that perhaps the technique gets used poorly in the field, leading to complicated code. Possibly there's a compiler implementation difficulty. For example, doing the equivalent of a C# virtual method -- a sequence of abstract, default, augmentation (see: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/methods) results in "error FS0359: More than one override implements". Oops... that's a bit awkward.

Possibly, this only impacts people attempting a final OO for some kind of API level abstraction. It's not a big impact. I'm curious to know the thinking behind outlawing this practice.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: 

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by cartermp** [comment] 2018-09-10 16:08
> I propose we continue to allow this kind of augmentation. modules are a nice home for functions. Blending them together with the type augmentations is (or was) a nice technique.

This seems unrelated to using overrides in type augmentations. So long as you don't override an existing member, there's nothing stopping you from having a type augmentation call a function in a module:

```
> type SomeType() =                                                                                                                                                                           
-   member this.SomeMethod() = "hello"                                                                                                                                                        
-                                                                                                                                                                                             
- module SomeType =                                                                                                                                                                           
-   let helper = id;;                                                                                                                                                                         
type SomeType =                                                                                                                                                                               
  class                                                                                                                                                                                       
    new : unit -> SomeType                                                                                                                                                                    
    member SomeMethod : unit -> string                                                                                                                                                        
  end                                                                                                                                                                                         
module SomeType = begin                                                                                                                                                                       
  val helper : ('a -> 'a)                                                                                                                                                                     
end                                                                                                                                                                                           
                                                                                                                                                                                              
> type SomeType with                                                                                                                                                                          
-     member __.Foo x = SomeType.helper x;;                                                                                                                                                   
type SomeType with                                                                                                                                                                            
  member Foo : x:'a -> 'a                                                                                                                                                                     
                                                                                                                                                                                              
> let s = SomeType();;                                                                                                                                                                        
val s : SomeType                                                                                                                                                                              
                                                                                                                                                                                              
> s.SomeMethod();;                                                                                                                                                                            
val it : string = "hello"                                                                                                                                                                     
                                                                                                                                                                                              
> s.Foo 12;;                                                                                                                                                                                  
val it : int = 12                                                                                                                                                                                                                                                                                                                                                                   ```

> Will it get elevated, eventually, or is this merely a style-cop kind of rule that's migrated into the compiler?

I suspect it will eventually be elevated to a compile error. I don't find it likely that a deprecation warning would back off back to being allowable.

**Comment by sgtz** [comment] 2018-09-10 21:12
"This seems unrelated to using overrides in type augmentations. So long as you don't override an existing member, there's nothing stopping you from having a type augmentation call a function in a module:"

it 'twas the getting things ready for wider CLR consumption stage where this feature was useful. .ToString() for example.

Assuming one was bent on doing it this way (I abandoned this idea)... 
• type A, 
• module that interacts with A + makes available pretty printing for fsi.
• type augmentation of A where overloads happen (like .ToString()).

"I suspect it will eventually be elevated to a compile error." 

I feared that would be the case. Once, I remembered that this used to work okay. Moving with the times... is there a reason why lurking around somewhere? 

Another alternative is overusing static members, and throwing more logic inside the type... or extending the *and* keyword to modules.

Using your suggestion, I could now have:

    .BetterToString()

**Comment by gusty** [comment] 2018-09-11 09:02
This seems to be related to this discussion https://github.com/Microsoft/visualfsharp/issues/3692

**Comment by cartermp** [comment] 2018-09-11 15:54
@sgtz I think the decision for something like this is that if you cannot control a type's definition and still want to override a member like `ToString()`, then writing a helper function that does what you need instead is preferred.

**Comment by reinux** [comment] 2019-07-09 20:28
How about for intrinsic type extensions that implement interfaces?

I have an AST, followed by a module that generates tokens for each of the nodes. Would be cool if I could then implement a ITokens interface for each of the nodes so that I don't have to look for the right print function or use type test patterns or put ITokens implementations among the definition of each type.

**Comment by gusty** [comment] 2021-02-26 05:22
Yes, I second @reinux  proposal, what's wrong with being able to write the `interface ISomething with ...` further down in the same file?

Right now we're forced to "pollute" our business logic with all the interface code for each aspect, it would be nice if we could move all the aspects further down, separating effectively from Business Logic.

**Comment by dsyme** [comment] 2021-03-01 15:16
> Yes, I second @reinux proposal, what's wrong with being able to write the interface ISomething with ... further down in the same file?

The problem is that no static state initialization checks are made for the case where this enables forward calls via the interface during file initialization.

This is obviously extremely rare and also not a problem when "namespace rec" is used.

So the limitation could maybe be best turned into a warning when "namespace rec" is not used, and removed altogether when it is.

**Comment by dsyme** [comment] 2021-03-01 15:17
I've marked this as approved in principle for this design: 

> So the limitation could maybe be best turned into a warning when "namespace rec" is not used, and removed altogether when it is.

**Comment by dsyme** [comment] 2021-06-30 22:39
I've clarified the approved suggestion in https://github.com/dotnet/fsharp/pull/11170#issuecomment-871772012

**Comment by dsyme** [comment] 2022-10-28 15:05
This has been completed, thanks

**Closed by dsyme** 2022-10-28 15:05 UTC
Labels: approved-in-principle, area: extension-methods, good first issue
