### ISSUE TITLE
Warn on implicit type functions, or an attribute to memoize them using type-indexed table [ RFC FS-1038 ]

### ISSUE THREAD

**Issue by jack-pappas** [fsharp/fslang-suggestions#602] opened 2017-08-12 20:45 UTC
I propose a modification to the way the compiler emits code for module-scoped, let-bound values decorated with ``[<GeneralizableValue>]``.

When defining a type-indexed, generalizable value, like so:
```fsharp
module MyModule =
    [<GeneralizableValue>]
    let foo<'T> = typeof<'T>.Name
```
the compiler changes the compiled representation of the value from a static field into a static method. This means the value is really changed to a function, and the expression bound to the value is re-evaluated each time the value is used. In other words, the compiler produces code that'd decompile into something like the following C# code:
```csharp
static class MyModule
{
    public static string foo<T>()
    {
        return typeof(T).Name;
    }
}
```

If the compiler generated a slightly more-complex backing representation for each 'generalized' value, we could get the benefits of type-indexed values without having to re-evaluate the expression each time the value was used. My suggestion is that, for each such field, the compiler generates a nested, private, static, generic, ``beforefieldinit`` class containing a private, static, readonly field and a public get-only property to fetch the field's value. The expression (rhs) being bound to the generalizable value would be compiled into this class' static constructor (``.cctor``) and used to initialize the readonly field within the class. The compiler would still also emit a static method for the generalizable value, but instead of re-evaluating the expression, the method would simply call the property getter to fetch the evaluated, cached value from within it's corresponding static class. To illustrate, the code emitted for the value would decompile to something like the following C# code:
```csharp
static class MyModule
{
    [CompilerGenerated]
    private static class foo__BackingField<T>
    {
        private static readonly string __value = typeof(T).Name;

        public static string Value { get { return __value; } }
    }

    public static string foo<T>()
    {
        return foo__BackingField<T>.Value;
    }
}
```

## Pros and Cons 

The advantages of making this adjustment to F# are:

- Expressions bound to ``let``-bound values decorated with ``[<GeneralizableValue>]`` are evaluated only once, just like any other let-bound value would be.
- _May_ provide a small performance improvement for cases where it's expensive (for one reason or another) to evaluate the expression being bound to the value.

The disadvantages of making this adjustment to F# are:

- Code which currently relies on the multiple-evaluation aspect of ``[<GeneralizableValue>]`` would break.
- Could increase memory usage and/or change GC characteristics due to actually caching evaluated values; they'll be stored in static fields, so if the values are instances of reference types they'll become GC roots.
- Small increases in compiled binary sizes due to the additional metadata for the generated backing classes.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): *S*

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [✓] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [✓] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [✓] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [✓] This is not a breaking change to the F# language design
* [✓] I or my company would be willing to help implement and/or test this

**Comment by jack-pappas** [comment] 2017-08-12 20:47
For additional background information, see this article "Finer Points of F# Value Restriction":
https://blogs.msdn.microsoft.com/mulambda/2010/05/01/finer-points-of-f-value-restriction/

**Comment by dsyme** [comment] 2017-08-14 14:09
@jack-pappas I like this suggestion.  I suppose it is in theory a breaking change if the evaluation has an observable side-effect.  But GeneralizableValue is extremely rarely used, and the intent is that it is only used in situations where amortization is reasonable, so I don't think that's actually a problem in practice

**Comment by jack-pappas** [comment] 2017-08-14 18:06
Thanks! Should I write up an RFC for this?

**Comment by dsyme** [comment] 2017-08-14 18:34
Yes, marking as approved

**Comment by jack-pappas** [comment] 2017-08-27 15:05
I've submitted an RFC (FS-1038) to fslang-design so we can start working out the details.

**Comment by dsyme** [comment] 2017-08-29 12:27
@jack-pappas I'll leave the suggestion open so people can find it

**Comment by eiriktsarpalis** [comment] 2017-08-29 12:55
@dsyme @jack-pappas the proposed change would irrevocably break certain applications where it is required that a fresh object be returned when invoked for reference types. Check [this example](https://github.com/eiriktsarpalis/TypeShape/blob/master/samples/empty.fsx#L161) for instance.

**Comment by dsyme** [comment] 2017-08-29 13:01
@eiriktsarpalis Interesting, thanks. 
@jack-pappas Using opt-in for the generation of a type-specific backing field would solve this:

```
    [<GeneralizableValue(unique=true)>]
    let foo<'T> = typeof<'T>.Name
```

**Comment by eiriktsarpalis** [comment] 2017-08-29 14:24
@dsyme @jack-pappas would it make sense to include the `GeneralizableValue` attribute in code generation as well? It would solve one of the issues described [here](https://github.com/eiriktsarpalis/QuotationCompiler/issues/3).

**Comment by dsyme** [comment] 2017-08-29 18:27
@eiriktsarpalis Yes.  Though do you also need it for generalized values without the attribute  like 

```
let x = [[]]
```
?

**Comment by eiriktsarpalis** [comment] 2017-08-29 21:11
Yes, anything of that sort.

**Comment by jack-pappas** [comment] 2017-09-10 16:40
According to the blog post I linked above:

> If you end up writing a type-parametrized function returning mutable objects or having side effects, please do sprinkle a RequiresExplicitTypeArguments attribute over it:
> ```fsharp
> [<RequiresExplicitTypeArguments>]
> let v<'T> : 'T list ref = ref []
> ```

Sounds that's what should be used instead of adding a ``Unique`` property to ``[<GeneralizableValue>]``?

**Comment by dsyme** [comment] 2017-09-10 16:46
@jack-pappas ``RequiresExplicitTypeArguments`` is a very syntactic thing. I think adding the flag to ``GeneralizableValue`` is right

**Comment by abelbraaksma** [comment] 2017-09-19 21:02
> Using opt-in for the generation of a type-specific backing field would be a way forward with this:

@dsyme, you suggest `unique = true`, but that may be misinterpreted, as it may also mean: getting a unique (reference) value each time the value is used, as in @eiriktsarpalis's example.

perhaps the following would be more self-explanatory?

```f#
[<GeneralizableValue(initializeOnce=true)>]
let foo<'T> = typeof<'T>.Name
```

**Comment by dsyme** [comment] 2017-09-20 17:27
@abelbraaksma Yes, that would be fine.  Or ``amortized`` or ``once`` is fine too, other suggestions welcome

**Comment by matthid** [comment] 2017-09-20 17:55
It would be really unfortunate if we cannot fix this. 
It doesn't look like a function and additionally the attribute says it's a "value".

Was it clearly speced to behave like this or was the implementation just an oversight (= read bug)?

**Comment by dsyme** [comment] 2017-11-16 14:24
> Was it clearly speced to behave like this or was the implementation just an oversight (= read bug)?

It was intended - I'm not saying the name was good though.  

The idea was "the library designer intends to implement something that feels like a value to the user of the library (like ``Set.empty``) and thus needs it to be generalizable"

Note that it is _not_ ``GeneralizableValue`` that actually causes the use of a type function.  The effect of ``GeneralizableValue`` is to make _uses_ of a thing generalizable, e.g. c.f.

```fsharp
type Set<'T>() = class end

let empty<'T> = Set<'T>()

let zero = [ empty ] // value restriction
```
c.f.
```fsharp
type Set<'T>() = class end

[<GeneralizableValue>]
let empty<'T> = Set<'T>()

let zero = [ empty ] // no value restriction, implicit type function
```

As a result I don't think adjusting the GeneralizableValue attribute is really what you're after - a new ``TypeIndexedValue`` attribute may be better

**Comment by dsyme** [comment] 2017-11-16 14:27
@jack-pappas I've adjusted the title of the suggestion - RFC will need to be updated too?

**Comment by gusty** [comment] 2019-07-12 05:48
Another thing that I think it's annoying, is the fact that let bound values/functions for custom numbers defined within the `NumericLiteralX` module are evaluated each time.

This force the user to store the literals somewhere in order to speed up calculation, which defeats the purpose of a numeric literal.

There must be a way to avoid this, treating them really like literals, at least the `zero` and `one` but I think there might be a way to implement some logic in the compiler to avoid calling twice the functions with the same arguments.

**Comment by dsyme** [comment] 2019-07-12 10:14
Yes, someone needs to add an optimization in IlxGen.fs or elsewhere to statically store constants (including constructed immutable data and closures).  Careful performance testing would be needed but it will be worth it.

**Comment by dsyme** [comment] 2021-01-27 15:04
> Yes, someone needs to add an optimization in IlxGen.fs or elsewhere to statically store constants (including constructed immutable data and closures). Careful performance testing would be needed but it will be worth it.

Note this has recently been done for closures. It would be great if someone did it for numeric constants and other immutable data constructions as well

**Closed** 2022-10-27 13:35 UTC
Labels: area: dotnet-codegen

**Comment by IS4Code** [comment] 2025-02-13 10:38
Could this suggestion be revised? The fact that you cannot even distinguish in syntax whether a "variable" is secretly a function and evaluated every time is concerning to me.

In my situation, I would also like "`TypeIndexedValue`" be applicable to a module as a whole too, affecting all variables within.

Having this as an option would also allow `mutable` variables of this sort, just returning a reference to the backing field.
