### ISSUE TITLE
Return untyped syntax tree from ITypeProvider

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#123] opened 2016-10-20 01:41 UTC
**Submitted by Isak Sky on 7/13/2016 12:00:00 AM**  
**27 votes on UserVoice prior to migration**  

Add the ability to *opt in* to send back an untyped syntax tree from ITypeProviders. The current type provider mechanism is good for simple data exploration use cases, but otherwise extremely limited, and will soon allow for less metaprogramming than Roslyn in some ways. Currently, some types of type providers not possible to create, because unbound generics, records, discriminated unions, and other normal language features are not supported.

With the ability to opt in to just returning an untyped syntax tree, it would enable the creation of just about any type provider. It would also effectively give F# macros, though through an API rather than syntax.

These new kind of type providers would be hard to create initially, but the community would be empowered to create libraries to wrap the untyped syntax tree to make it easier to use, and it would soon be an extremely effective and powerful way to do metaprogramming.

Another benefit is that there wouldn't really be much of a design to experiment with to get right - it is just the untyped syntax tree of the language, which we already have a version of.

The F# community has very limited resources, and this would be an extremely leveraged way to utilize them.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/15202209)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-15202209-return-untyped-syntax-tree-from-itypeprovider.md#comments)

**Comment by dsyme** [comment] 2016-10-29 16:34
Really a duplicate of #210

**Closed by dsyme** 2016-10-29 16:34 UTC
Labels: old votes:11-50

**Comment by isaksky** [comment] 2018-12-21 18:59
Rust now supports this.

```rust
#[proc_macro_attribute]
pub fn hello(attr: TokenStream, item: TokenStream) -> TokenStream {
    // ...
}
```

[Procedural Macros in Rust 2018](https://blog.rust-lang.org/2018/12/21/Procedural-Macros-in-Rust-2018.html)
