### ISSUE TITLE
Allow #package directives to import NuGet packages in F# scripts

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#198] opened 2016-10-20 01:51 UTC
**Submitted by Jack Pappas on 3/23/2014 12:00:00 AM**  
**248 votes on UserVoice prior to migration**  

It would be quite useful for F# interactive to support a #package directive to allow NuGet packages to be downloaded from within the REPL. I think it would be best if this directive simply downloaded the package, unpacked it, and automatically included (#I) the correct folder based on the framework version F# interactive is running under (e.g., net45). If a package doesn't include assemblies for the specific framework version F# interactive is using, we'd automatically include the folder for the latest framework version which is compatible; e.g., if running on .NET 4.5 and a package only includes a 'net40' folder, we'd include (#I) that folder. I believe this behavior is consistent with how NuGet currently works when referencing packages from a project, e.g., in Visual Studio.
# package should not, however, automatically reference (#r) the assemblies included in the package, in case you only want to reference some of them.

Here's a usage example:

```
#package "ExtCore.0.8.41"
#r "ExtCore.dll";;
let substr = substring "Hello World!"
printfn "Value: %O" substr;;
```

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/5670137)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-5670137--package-directive-to-import-nuget-packages-in-f.md#comments)

**Comment by JanWosnitza** [comment] 2016-12-22 12:41
> package should not, however, automatically reference (#r) the assemblies included in the package, in case you only want to reference some of them.

I don't see any advantage in having to reference every dll manually. Even worse, it requires the script to have knowledge of the package's structure.

**Comment by Rickasaurus** [comment] 2016-12-23 18:07
This would be great to have, but as Paket work has shown, there's a lot of edge cases with nuget beyond just referencing libraries. What if we could have something like a Paket def in FSI? They've already solved a lot of the hard problems.

**Comment by dsyme** [comment] 2017-03-01 15:17
Closing as a duplicate of the more active discussion https://github.com/fsharp/fslang-suggestions/issues/542

**Closed by dsyme** 2017-03-01 15:17 UTC
Labels: old votes:201-300, under-review
