### ISSUE TITLE
What happened to the archives user voice comments? 

### ISSUE THREAD

**Issue by abelbraaksma** [fsharp/fslang-suggestions#800] opened 2019-10-26 23:51 UTC
Not really a suggestion, but a big bug in this github repo: the archived UserVoice comments are gone. 

Since we are expected to research prior discussions before suggesting a new feature, I'd love them to come back. It's also very worthwhile to read why something was accepted or declined in the past. 

Example where the link is broken (but it's true for all): https://github.com/fsharp/fslang-suggestions/issues/371.

@baronfel, pinging you as you seem to have been the one doing the original migration from UserVoice.

**Comment by cartermp** [comment] 2019-10-27 01:01
Most likely because the account associated with it was shut down, much like the old Visual Studio uservoice items.

**Comment by abelbraaksma** [comment] 2019-10-27 11:50
@cartermp, er was why it was archived, the comments were moved to github. Location:

    https://github.com/fsharp/fslang-suggestions/tree/master/archive/suggestion-6730304-add-try-with-finally-for-consistency.md#comments

But that doesn't exist anymore.

**Comment by smoothdeveloper** [comment] 2019-10-27 14:12
@abelbraaksma is https://github.com/fsharp/fslang-suggestions/blob/d48c35ce216e2bff148937ec028ad61e5c273fdf/archive/suggestion-6730304-add-try-with-finally-for-consistency.md OK

You can see "View all archived uservoice suggestions and comments" section on repository root: https://github.com/fsharp/fslang-suggestions

**Comment by Happypig375** [comment] 2019-10-28 09:58
Duplicate of #735

**Closed** 2022-06-16 10:19 UTC
