### ISSUE TITLE
Change default reported type for arrays

### ISSUE THREAD

**Issue by ReedCopsey** [fsharp/fslang-suggestions#635] opened 2018-01-10 20:07 UTC
I propose we change F# lists reported type annotations to always use `array` instead of `[]`. The existing default causes significant confusion, especially to people new to F#.

For example, the following output in FSI is incredibly confusing because it's apparently inconsistent to new users:

```fsharp
> let x = []
let y = [| |];;
val x : 'a list
val y : 'a []
```

While lists are declared using `[ ]`, the type annotation shows `list`. Arrays, however, are declared using `[| |]`, but the type annotation shows `[]`, which "looks like an array" to new users. We very frequently get questions from people who are very confused when coming to F# because of this.

I propose to change type annotations which are *reported* (tooltips, FSI, intellisense) to display as this instead:

```fsharp
> let x = []
let y = [| |];;
val x : 'a list
val y : 'a array
```

Note that I am not suggesting changing or breaking compatibility. Using `[]` should still be allowed in manual type annotations. Today, you can easily use `[]` or `array` interchangeably. I am merely suggesting that all tooling should switch to suggesting `array`, as it'd be more in line with `list`, but also less confusing to new users.

## Pros and Cons 

The advantages of making this adjustment to F# are consistency for new users. Arrays would be obvious as arrays instead of being confused as lists.

The disadvantages of making this adjustment to F# are that it's a change from previous behavior.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  S?

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [X] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [X] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [X] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

**Comment by enricosada** [comment] 2018-01-10 20:10
backward compatibility aside, 💯 this.
if need to happen in F# 5.0 ok, but is really nice to have it scheduled.

parser need anyway to know that `val y : 'a array` is the same as `val y : 'a []` so..

**Comment by ReedCopsey** [comment] 2018-01-10 20:12
Yes - I wasn't suggesting making any changes to parsing - merely to what gets reported by FSI/tooltips and other annotations in the language service/etc. This is a "change how the tooling reports" vs "change the language" suggestion.

**Comment by enricosada** [comment] 2018-01-10 20:13
i written that badly.
i mean any code out there should already known are equivalent, so is not much a breaking change. see fsdn.azurewebsites.net allow both

**Comment by ReedCopsey** [comment] 2018-01-10 20:16
Yes. It's likely that some tests which parse the output of FSI or tooling would likely fail, since they likely make the assumption that array will annotate as `[]`, but actual production code should be completely backwards compatible.

**Comment by realvictorprm** [comment] 2018-01-11 06:50
This is a small change with great effect for newcomers, thanks @ReedCopsey

**Comment by isaacabraham** [comment] 2018-01-15 09:11
Also, you can already use `array` instead of `[]` syntax e.g. `{ Customers : Customer array }` (which I actually happen to prefer) so this fits in anyway.

**Comment by pblasucci** [comment] 2021-08-30 21:18
I think this would be a wonderful improvement. :100: 

Though I might go further and issue a warning (or maybe use an analyzer) for the other, less desirable forms (`int[]` and `array<int>`). There's precedence for this already (cf: the warning you get for writing `let lookup : (string, int) Map = Map.empty`).

**Comment by dsyme** [comment] 2021-08-30 21:50
Please vote on this issue.  

👍 - change all tooling printing `int array`, `int list`, `int option`, 
👎 - keep tooling printing `int[]`, `int list`, `int option`

Thanks

**Comment by jbeeko** [comment] 2021-08-30 21:51
```
let foo: string list = ["foo"]    // val foo : string list = ["foo"]
let foo' = ["foo'"]               // val foo' : string list = ["foo'"]

let bar: string array = [|"bar"|] // val bar : string array = [|"bar"|] 
let bar' = [|"bar'"|]             // val bar' : string [] = [|"bar'"|] 
```

Above are four let bindings and what the FSI reports. If I understand what is being suggested here it is that the last binding should be reported as `val bar : string array = [|"bar"|] ` across the board.

And yes that did confuse me when I was new to the language. Actually still occasionally gives me a jolt.

**Comment by baronfel** [comment] 2021-08-30 22:15
If this doesn't change at the language level I was going to add a DisplayEnv flag specifically for this (in the same way as we added the option to specify explicit postfix/prefix type arguments during type name formatting) just to address Ionide user feedback. So I'm two thumbs-up :D

**Comment by dsyme** [comment] 2021-08-30 22:37
> Though I might go further and issue a warning (or maybe use an analyzer) for the other, less desirable forms (`int[]` and `array<int>`). 

Yes, I think we would emit an informational (weaker than a warning, like a lint message).

> There's precedence for this already (cf: the warning you get for writing `let lookup : (string, int) Map = Map.empty`).

This has long been deprecated and we're making it an error, see https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1114-ml-compat-revisions.md

**Comment by dsyme** [comment] 2021-08-30 22:38
Marking this approved as with +20 votes to 0 it's obvious which way this is going

**Comment by dsyme** [comment] 2021-08-30 22:39
> just to address Ionide user feedback

@baronfel I'd like to understand where Ionide makes any decisions different to F# compiler defaults, if any, thanks

**Comment by gbaydin** [comment] 2021-08-30 22:50
What about the implications of this for multidimensional arrays, e.g., `'T[,,,]` ?

Here's a screenshot from the vscode + ionide tooling I use on linux: 
![Untitled](https://user-images.githubusercontent.com/5365982/131415150-e8cb9106-a961-4557-9820-fa53286c776d.png)

The tooling shows two types of annotations in different places:
* `'T array -> 'T array * int array`
* `[,,,]<'T> -> []<'T> * []<int>`

Confusingly we can write the same thing as follows as well, I think:
* `'T[,,,] -> 'T[] * int[]`

To be honest, losing the multidimensional information in the annotation is not great if this proposal would map both `[,,,]<'T>` and `[]<'T>` to `'T array` as in the screenshot.

**Comment by baronfel** [comment] 2021-08-30 23:15
@gbaydin I'd first want to verify that the tooltip display in FSAC/Ionide isn't at fault there (rendering `'T array` instead of something more like `array<,,,,>`)

@dsyme the main things I'm aware of are
* prefer postfix type arguments (list<'T>)
* different decisions around tooltips (with regards to layout, content, what xmldoc elements to include)

@Krzysztof-Cieslak any other large areas jump out at you where we make other formatting decisions?

**Comment by kekyo** [comment] 2021-08-30 23:32
I wondered how to match it with the symbols in the array, `int [||]`.  The word `array` seemed to mean something else, and I didn't know if I would get used to it (it's a subtle issue).
In that case, it may be better to write `list` as `int []`, but it is annoying because it can be mistaken for an array...

**Comment by dsyme** [comment] 2021-08-30 23:37
I think there are some bugs in the Ionide type presentation.  Even for `main` the `argv` type is shown as `[]<string>` or something like that.

@gbaydin Yes, we would have to address 2D, 3D, 4D, 5D, 6D arrays as part of this.  Realistically we could just normalize to 

```
    int array
    int list
    int option
    int array2d
    int array3d
    int array4d
    int array5d
    int array6d
```

Up to some fixed size (there is already a limit of 32 in FSharp.Core so I guess we use that, though that's considerable pollution in autocomplete menus)

**Comment by baronfel** [comment] 2021-08-30 23:46
@dsyme that case in particular is one that would be solved by this issue, and is caused by using the new forced postfix representation. My presentation fix had unforeseen consequences!

**Comment by dsyme** [comment] 2021-08-30 23:52
@baronfel OK thanks :)

> prefer postfix type arguments `list<'T>`

Hmmm, I see, I'd always thought this was just a bug in Ionide.  TBH I'd rather Ionide didn't do this - we really need to be consistent and make these decisions across the whole ecosystem - it's really hard VS and Rider and F# Interactive are printing things one way and then VSCode does it another. The current F# style guide has pretty clear guidance on this one too :)

https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#use-prefix-syntax-for-generics-foot-in-preference-to-postfix-syntax-t-foo

(though here we're looking at changing the array guidance of course, but let's do it consistenly)

**Comment by dsyme** [comment] 2021-08-31 00:04
> TBH I'd rather Ionide didn't do this for list, option, voption, ref, array - we really need to be consistent and make these decisions across the whole ecosystem

@baronfel I'm happy to prep a fix to align Ionide to the existing F# style guide - any pointers to where the type printing is located?  (I can dig around and find it no probs)

**Comment by charlesroddie** [comment] 2021-08-31 11:51
> we really need to be consistent

The common approach in F# is to use prefix type arguments for a curated set of types and postfix arguments for all other generics, so it's not consistent. I don't see anything in the style guide about this, but the [generics section of the language reference](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/generics) doesn't mention prefix type arguments. I recommend staying with the status quo in the style guide and generics reference since they both reflect common usage, but since the common usage is inconsistent it shouldn't be explicitly recommended.

Personally I would definitely set "prefer postfix type arguments" on everything if given the choice.

That said, the proposed change, which doesn't affect prefix/postfix, is good.

**Comment by deviousasti** [comment] 2021-08-31 11:59
Postfix makes for much less readability from a DDD perspective. 
```
states : Aggregate versioned list
```
makes for much easier reading than
```
states : list<versioned<Aggregate>>
```

**Comment by dsyme** [comment] 2021-08-31 13:06
> I don't see anything in the style guide about this

The style guide does address this? https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#use-prefix-syntax-for-generics-foot-in-preference-to-postfix-syntax-t-foo. Or were you referring to something else?

> The generics section of the language reference doesn't mention prefix type arguments. 

It should, you're correct

> I recommend staying with the status quo in the style guide and generics reference since they both reflect common usage, but since the common usage is inconsistent it shouldn't be explicitly recommended.

I consider these two different inconsistencies, and I only really want to deal with one here, which is `int[]` v. `int array`/`int list`.  The feeling in the community is strongewr than I realised about this.

The inconsistency between `int list` and list<int>` does feel like a different discussion, though I feel we can't really even have that discussion without first considering the array inconsistency, and they are orthogonal.

> Postfix makes for much less readability from a DDD perspective.

I do find this too.  Equally, I am aware this has inflicted the second inconsistency on the F# world, but I see why it's happened.  I'm also aware that as soon as a type has any significant computational content (e.g. even `int seq`) I don't like prefix type arguments.  I'm also aware I don't like postfix type arguments for function types.  This is why we ended up with the very restricted set of types where we declared it "ok" to place the type constructor last (`int list`, `int option`, `int voption`, `int ref`, `int array`).  It's notable that several of these cases have logically corresponding postfix syntax counterparts in C# (`int[]`, `int?`) so it does seem that these are so fundamental to domain modelling that it's not wrong for languages to have exceptions for them.

Anyway, it's a separate discussion I think, let's not rathole on it in this discussion thread.  If someone wants to propose removing the specific exceptions in the style guide for `int list`, `int option`, `int voption`, `int ref`, `int array` please make a suggestion, it's not something I'm pushing however.  

Aside: we get into terminology problems, so please always try to be clear via examples. Generally we would normally talk of the type constructor `list` or `array` being the thing that is prefix/postfix/infix, like `++` is prefix/postfix/infix, though in most the discussion in the thread people are referring type arguments.  So beware this when commenting:

* "Postfix type arguments" = "Prefix type constructor"
* "Prefix type arguments" = "Postfix type constructor"

**Comment by dsyme** [comment] 2021-09-05 15:40
Although I've marked this as approved-in-principle, this is not yet actioned, and `int[]` is still regarded as the default for array type presentation in tooling and in the F# style guide 

The order should be

1. update F# core tooling to use `int array` byt default in some specific language version (likely F# 6.1, if such a number gets used)
2. update F# Ionide and F# docs likewise (these could happen earlier)
3. update the F# style guide

I'd be interested if there are other changes that people think should be made.

**Comment by pblasucci** [comment] 2021-09-05 16:28
This seems like a good plan. But to clarify, when you say "F# Docs", @dsyme, do you mean:

- FSharp.Core API reference
- F# materials hosted by Microsoft (independent of the style guide)
- Both

I'm assuming you mean the first of these (but I hate too assume).

**Comment by dsyme** [comment] 2021-09-06 14:15
I mean both

**Comment by dsyme** [comment] 2022-10-28 14:35
The next steps are:

* update F# Ionide
* update F# docs at docs.microsoft.com/dotnet/fsharp
* update the F# style guide at docs.microsoft.com/dotnet/fsharp
* update FSharp.Core API reference

**Comment by edgarfgp** [comment] 2023-01-22 17:37
@vzarytovskii From a implementation POV this is done :) . I created a dedicated issue in `fsharp` repo https://github.com/dotnet/fsharp/issues/14329 to track the remaining work . I was wondering of we should mark this one as done to avoid confusion ?

**Closed** 2023-04-12 13:56 UTC
Labels: approved-in-principle, area: tooling, proposed-priority
