### ISSUE TITLE
Enable pattern matching on more specific types from type test patterns

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#1025] opened 2021-06-07 17:03 UTC
# Enable pattern matching on more specific types from type test patterns

I propose we allow:
```fs
type DU = DU of int * int
let (|Id|) = id
match box (1, 2) with
| :? (int * int) as (x, y) -> printfn $"A tuple: {x}, {y}"
| :? struct(int * int) as (x, y) -> printfn $"A struct tuple: {x}, {y}"
| :? DU as (DU (x, y)) -> printfn $"A DU: {x}, {y}"
| :? int as (Id i) -> printfn $"An int: {i}"
| _ -> printfn "Nope"
```

The existing way of approaching this problem in F# is to have an extra level of `match` expressions.

## Pros and Cons 

The advantages of making this adjustment to F# are
1. Conciseness
2. Convenience
3. Composability

The disadvantage of making this adjustment to F# is that this makes inheritance-based code easier.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S to M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment] 2021-06-07 21:49
I don't think F# should add features to make type tests easier. They should not be part of the standard toolkit.

**Comment by Happypig375** [comment] 2021-06-08 04:11
I believe that this would complement #538 quite nicely. Now that direct type unions are allowed, we should be able to match on them more effectively.

**Comment by dsyme** [comment] 2021-06-08 18:41
> I don't think F# should add features to make type tests easier. They should not be part of the standard toolkit.

For me this is more about language uniformity.  It's reasonable to make these things more orthogonal

**Comment by dsyme** [comment] 2021-06-08 18:48
Indeed `:? type as ident` should always really have been `:? type as pat`

**Comment by Happypig375** [comment] 2021-06-10 09:30
Also there is the inconsistency that `:? type as ident` has the derived type for `ident`, but `a & :? type as ident` does not. An alternative route would be to fix `&` such that the correct type is inferred for `&`s after the type test, but I guess breaking changed are still not allowed.

**Comment by Happypig375** [comment] 2021-06-10 09:30
Draft RFC here: https://github.com/fsharp/fslang-design/pull/595

**Comment by dsyme** [comment] 2021-06-12 12:38
Thanks, marked as approved in principle

**Comment by chkn** [comment] 2021-06-21 01:34
> | :? DU as (DU (x, y)) -> printfn $"A DU: {x}, {y}"

I'd love if this could just become

```fsharp
| DU (x, y) -> printfn $"A DU: {x}, {y}"
```

**Comment by Happypig375** [comment] 2021-06-21 05:35
@chkn The problem is with the change in type inference though.
```fs
let f = function DU (x, y) -> printfn $"A DU: {x}, {y}"
```
is inferred to be
```fs
val f : _arg1:DU -> unit
```
While changing to that would be
```fs
val f : _arg1:obj -> unit
```
With https://github.com/fsharp/fslang-suggestions/issues/968, you can use
```fs
let f = function :? DU (x, y) -> printfn $"A DU: {x}, {y}"
```
instead, which will have the correct type inference.

**Comment by dsyme** [comment] 2021-06-21 12:55
> I'd love if this could just become

When the input typs is an arbitrary object of type `obj` I believe we always want the `:?` type check cast to be explicit

**Comment by chkn** [comment] 2021-06-21 13:26
> When the input is an arbitrary object of type `obj` I believe we always want the `:?` type check cast to be explicit

Fair enough- makes sense in this case.

But perhaps we could allow for an implicit type check when the input is already known to be an anonymous union containing the type suggested by the pattern?

**Comment by dsyme** [comment] 2021-06-24 13:33
RFC is here: https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1105-Non-variable-patterns-to-the-right-of-as-patterns.md

**Comment by auduchinok** [comment] 2021-06-24 15:40
@dsyme The link points to 404.
I've seen it many times with other RFC links too.

**Comment by Happypig375** [comment] 2021-06-24 17:41
It's been moved to the preview folder.

**Comment by auduchinok** [comment] 2021-06-24 17:49
Yes, I'm able to find it, thanks. The problem is many of the RFC links become 404 due to being moved. Maybe we could find an approach that would preserve the links somehow?

**Comment by dsyme** [comment] 2021-06-24 19:39
Fixed thanks

Yes it's annoying but github doesn't give us any way, we'd have to publish a site

**Comment by smoothdeveloper** [comment] 2021-07-17 20:43
related or very close suggestion: #830

**Comment by dsyme** [comment] 2022-06-09 13:56
Implemented in F# 6

**Closed by dsyme** 2022-06-09 13:56 UTC
Labels: approved-in-principle
