### ISSUE TITLE
[Discussion] Finding F# language Suggestions

### ISSUE THREAD

**Issue by abelbraaksma** [fsharp/fslang-suggestions#525] opened 2016-12-14 00:15 UTC
# Finding F# Language suggestions

I propose to make it easier for people to find out how to make language suggestions to F#, and how to upvote such suggestions.

It's been only a few months ago since F# UserVoice was moved to Github, and I think for good reasons, but I have the feeling that it is now hard to find and even if you find it, and take the time to make a suggestion, that you have little chance of many people seeing it, let alone commenting on it, especially from outside the community.

I have some idea that may improve this but I'd like to hear from other people whether they think this is necessary and/or what improvement suggestions they have. I volunteer to do whatever needs to be done as today I got frustrated by again not finding this site quickly and would very much like to fix it.

# Suggestions

1. People should be able to find us:
    1. Create a link back to the new Github issue from each UserVoice issue
    2. Improve on keywords, i.e., this is not good (test with Opera):
![image](https://cloud.githubusercontent.com/assets/16015770/21164361/bd75f882-c198-11e6-9239-ae9af892fea9.png)
    3. Make the tagline for UserVoice very brief, so that in Google Results it is clear it has moved, i.e. "New ideas and suggestions for F# should be reported at ..." 
2. Instruct people quickly and easily
    1. the intro on github is very good and thorough, but if you're new and you have a great idea than in today's fast-paced world you won't read 15 min on guidelines just to get your idea across. Perhaps a TLDR version on top?
    2. this may well lead to some garbage proposals, but I think we have enough tools on our hands to remove/hide/close them quickly
3. Make finding suggestions easier (I hardly manage to find what I want). This is hard to get right, but:
    1. Use tags abundantly for, well, tagging by feature
    2. Group them (language, library, visual studio, repl)
    3. See the votecount in search results (may not be trivial: that is not a feature of Github, I think)
4. Guide people to the correct location
    1. A link to this homepage from Microsoft's and MSDN's homepage perhaps?
    2. Any of the well-known F# bloggers can give some exposure, maybe even write an article emphasizing the "openness" of F# and how to contribute?
5. Somehow make people understand "how to vote"
6. Convert the UserVoice community:
    1. Reach out by emailing them (which may happen by 1.i. above)
    2. Suggest they create a Github account
    3. Inform owners of UserVoice issues that their issue is moved
7. It would be wonderful if the tagged uservoice up-count could be converted into actual votes (but my guess is, this is impossible without cheating)

I'm sure this list is not exhaustive, but before it gets too long and people steer away, I'll stop now. Not everything is of equal importance or equally easy to establish. But if anything, I think we should get out of hiding and into the light ;).

**Comment by kerams** [comment] 2016-12-14 12:28
>4. Guide people to the correct location
A link from fsharp.org would be great (if there isn't one). Perhaps somewhere in the Contribute section?

**Comment by baronfel** [comment] 2016-12-14 13:10
All links to user voice on fsharp.org and the fsharp core engineering websites have already been updated to point to this repo.

**Comment by abelbraaksma** [comment] 2016-12-14 13:28
> All links to user voice on fsharp.org and the fsharp core engineering websites have already been updated to point to this repo.

That's good. Now we should do that too for UserVoice itself, obviously, or create a general redirect script (if UserVoice supports that) so that Google picks it up as well.

**Comment by cloudRoutine** [comment] 2016-12-14 16:37
Is it really **that** hard to find?

![](http://i.imgur.com/paL9vnw.png)

> today I got frustrated by again not finding this site quickly and would very much like to fix it.

use a bookmark 😜 

> the intro on github is very good and thorough, but if you're new and you have a great idea than in today's fast-paced world you won't read 15 min on guidelines just to get your idea across. Perhaps a TLDR version on top

If someone can't read 15m of guidelines they probably shouldn't make a suggestion

> Somehow make people understand "how to vote"

see above

> Convert the UserVoice community:
> - Reach out by emailing them (which may happen by 1.i. above)
> - Suggest they create a Github account
> - Inform owners of UserVoice issues that their issue is moved

this seems excessive

> Make finding suggestions easier (I hardly manage to find what I want). This is hard to get right, but:
> - Use tags abundantly for, well, tagging by feature

including "tag" keywords in the comment text will improve search more than this

> language, library, visual studio, repl

While I agree there should be more "area" tags, I just want to point out library, visual studio, and repl all fall into areas that are predominantly outside of what suggestions here are supposed to focus on. But we can always have more flavors of rejected/declined tags. 😆  (but seriously I actually do want that)

> It would be wonderful if the tagged uservoice up-count could be converted into actual votes (but my guess is, this is impossible without cheating)

We investigated this, it wasn't possible, thus the tags

> See the votecount in search results (may not be trivial: that is not a feature of Github, I think)

this could be done with a script that checks the `+1` count from the API and then auto tags based on the amount.

If you really want to do things like having a much improved seach, showing vote counts in query results, and other various UX flourishes it could be done by building a github integration app on top of the API like how [waffle](https://github.com/integrations/waffle) does it. It could even be written in F# using [Fable](http://fable.io/)

I used to spend a lot of time on uservoice and since the move to github it seems like there's been a lot more activity and the quality of the suggestions and discussions has definitely improved greatly.  Sure it could be better, but even if we were to build a github integration app on top of the repo with all the bells and whistles of a bleeding edge web app, I doubt it'll translate into a meaningful improvement of what really matters, thoughtful, useful, and feasible suggestions.

But if you really want to waste a bunch of time making a silly web app, I have a github developer account and I'm down to work on it 😁 (more because it could have a wider application across the F# ecosystem and allow orgs to make repos specifically for suggestions and feature requests so issues on the codebase can be reserved for actual issues)

**Comment by abelbraaksma** [comment] 2016-12-15 02:00
> I used to spend a lot of time on uservoice and since the move to github it seems like there's been a lot more activity and the quality of the suggestions and discussions has definitely improved greatly. 

I had the opposite impression, hence this thread. Considering the response so far, I may have been wrong (oddly, had nobody reacted, my point would've been proven ;).

> But if you really want to waste a bunch of time making a silly web app, I have a github developer account and I'm down to work on it

Really? After you basically argue that it isn't necessary? I welcome it, I have very little knowledge of Github (I must be getting old, CVS, SVN, Hg, Bit, Git and some proprietary, I can't keep up apparently), but I'd be willing to spend some time with it, be it testing, developing. At the very least it'll be a learning experience ;).

> including "tag" keywords in the comment text will improve search more than this

I have no idea what that is. This shows my lack of knowledge, even after a year being somewhat "active". This may be at the root of me fearing that part of the community is not being reached. But if indeed the opposite is true (more exposure, better discussions), I just need to up my skills. I think I just miss the simple overview Uservoice (with its flaws) showed.

> use a bookmark

LOL. Last time I consciously did that was perhaps in the Netscape times ;)

> Is it really that hard to find?

Not if you know how to search.

> If someone can't read 15m of guidelines they probably shouldn't make a suggestion

I disagree. Not everyone has enough skills of language design, or even just search skills to find out their idea is useful/good/applicable/definable. However, such ideas may be good regardless, since they come from an F# user's point of view and once understood or translated into language-design parlor, it may end up a welcome addition to the language (I believe the struct-for-du discussion started that way, for instance).

Perhaps we could have a big button or link "Think you have a great idea? Please share!" and have them pitch the idea, perhaps guided by two or three simple screens. Just thinking out loud.

-----

But all in all, thank you for your response, it's good to hear that it has been an improvement. I just failed to see it.

_PS: I do think we ought to clean up UserVoice (link back and improve landingspage visibility and click-through, it's not clear it is "closed"). Just give me an account and I'll do it by hand, it's only a handful (300 or so) suggestions there anyway._

**Comment by dsyme** [comment] 2017-03-01 14:23
The most frustrating thing about the move to GitHub is the fact that now no one votes on suggestions any more.  Reactions are just not an adequate voting mechanism

From my perspective the vote counts were a crucial feedback mechanism, even if they didn't determine full priority order.

**Comment by smoothdeveloper** [comment] 2017-03-01 14:43
@dsyme I think we should advertise the migration to everyone who contributed to uservoice, do you have a way to send email to all those users?

I do vote on suggestions, and vote only on those I'm most supportive, on others I'll often comment to get some precisions etc. to make my mind.

**Comment by dsyme** [comment] 2017-03-01 15:46
@smoothdeveloper I think everyone knows that the move has happened - it's made plain enough on the UV site.

> I think we should advertise the migration to everyone who contributed to uservoice, do you have a way to send email to all those users?

The problem is with the lack of decent voting mechanism, and no good ability to rank by votes.   It's not our fault - it's a general problem that GitHub issues are just not designed as a voting mechanism.

> I do vote on suggestions, and vote only on those I'm most supportive, on others I'll often comment to get some precisions etc. to make my mind.

Thanks - the reactions +1/-1 we are getting are still useful.

**Comment by smoothdeveloper** [comment] 2017-03-01 15:58
@dsyme you can rank by vote in the issue list, using the `Sort` item:

https://github.com/fsharp/fslang-suggestions/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

The problem I'm seeing is that there are currently only 29 watchers on that repository, we probably want to have more of them, and hence I wonder if sending a mail to uservoice's users we had wouldn't fix that problem at least partially.

**Comment by dsyme** [comment] 2017-03-03 16:05
@smoothdeveloper It's true that raising the number of general watchers of the whole repo would be useful.  I'm not sure we can send to all UV users.  But we could raise awareness and encourage people to watch the repo more

**Comment by smoothdeveloper** [comment] 2017-03-03 16:22
@dsyme I believe you are the watcher of this repository who currently has the most followers on twitter, you should tweet to ask people to watch this space and to F# users to review suggestions and cast their votes :)

**Comment by cartermp** [comment] 2017-03-03 16:58
I think it will get better over time.  It takes a while for mindshare to shift over somewhere else.  While I sympathize with the voting mechanism not being as used here, I think that the overall quality of suggestions has improved dramatically.  Each suggestion reads as if it were thought about a bit more by the person suggesting it, and I think it's lead to more focused discussions in the issues as well.

**Comment by dsyme** [comment] 2017-11-16 13:06
I'm closing this old discussion

I'd greatly appreciate it if someone in the community takes on the task of "advertising" F# language suggestions and RFCs and regularly calling for contributions

**Closed by dsyme** 2017-11-16 13:06 UTC
Labels: discussion

**Comment by realvictorprm** [comment] 2017-11-16 13:30
@dsyme If I'm allowed to I would try to advertise a bit on Twitter :-)

**Comment by abelbraaksma** [comment] 2017-11-16 18:28
@dsyme, I agree, and thanks for closing my old question. @realvictorprm, everyone is allowed to promote F# ;).

I still find it very hard to understand what is being pursued, what is in a certain version and what the long- and short-term plans are. I know it is not an easy feat to make this understandable to a large audience (and most other open source projects, small and big, have similar issues), but if we do manage somehow, I still believe that would have a positive effect on "spreading the word".

**Comment by dsyme** [comment] 2017-11-17 14:01
> ...butif we do manage somehow, I still believe that would have a positive effect on "spreading the word".

Probably the best approach for communication is to focus on amplifying positive action - when people implement RFCs, or RFCs are approved and closed, or suggestions are made, or prototypes are submitted etc.  

I personally think the FSSF Core Engineering Effort can be a natural banner for this positive communication  (note: not really a "Group" and the FSSF Board are still considering how to progress this effort).
