### ISSUE TITLE
extend ComputationExpression builders with Map : m<'a> * ('a -> 'b) -> m<'b>

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#36] opened 2016-10-20 01:29 UTC
**Submitted by Georg Haaser on 1/31/2016 12:00:00 AM**  
**8 votes on UserVoice prior to migration**  

In many scenarios computation expressions could be executed way more efficiently when having just a little more information. The typical use-case for that would be something like

```fsharp
    async {
        let! a = something
        return 2*a
    }
```
which currently gets translated to:
```fsharp
    async.Bind(something, fun a -> async.Return(2*a))
```
By monad laws (borrowed from haskell here) this must be equal to:
```fsharp
    async.Map(something, fun a -> 2*a)
```
In many scenarios the latter can be implemented with a lot less overhead, so in my opinion it would be profitable to allow users to provide this "shortcut".

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/11661270)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-11661270-extend-computationexpression-builders-with-map.md#comments)

**Comment by dsyme** [comment] 2017-03-01 14:12
Going over old issues: just to say that I agree this is a reasonable suggestion.

**Comment by dsyme** [comment] 2017-11-16 13:50
Closing as duplicate of #579

**Comment by rmunn** [comment] 2017-11-17 07:52
Just a note that the conversion from UserVoice glitched on this issue: the two occurrences of `2_a` in the sample code should have both been `2*a`. There's no special meaning attached to the underscore here; the intended sample code is just "multiply `a` by 2".

**Comment by dsyme** [comment] 2017-11-17 13:00
@rmunn Thanks, fixed.

**Comment by Rickasaurus** [comment] 2018-03-05 21:19
Yes please. This is partly why the continuation monad is so crazy expensive right?

**Comment by jwosty** [comment] 2018-03-14 05:35
@dsyme needs-rfc tag can be removed

**Comment by dsyme** [comment] 2021-09-25 10:47
Was completed a while back

**Closed by dsyme** 2021-09-25 10:47 UTC
Labels: old votes:0-10, area: computation-expressions, completed
