### ISSUE TITLE
Support for IAsyncEnumerable

### ISSUE THREAD

**Issue by isaacabraham** [fsharp/fslang-suggestions#975] opened 2021-01-31 15:41 UTC
# Support for IAsyncEnumerable

I propose we add support for IAsyncEnumerable. I have no idea how that should be surfaced though - as a new computation expression / library support / language support etc.

Currently I'm seeing some libraries (notably the new Azure ones) expose data as IAsyncEnumerable which, out of the box, doesn't appear to have any way to be consumed in F#.

The existing way of approaching this problem in F# is to write code that can flatten an `IAsyncEnumerable<'T>` into e.g. `Task<'T array>`. Obviously this changes the semantics though and is not suitable in all cases. Alternatively, possibly the use of the AsyncSeq library could help.

```fsharp
type System.Collections.Generic.IAsyncEnumerable<'T> with
    member this.AsTask () = task {
        let mutable moreData = true
        let output = ResizeArray ()
        let enumerator = this.GetAsyncEnumerator()
        while moreData do
            let! next = enumerator.MoveNextAsync()
            moreData <- next
            if moreData then output.Add enumerator.Current
        return output.ToArray()
    }

....

task {
    let container = client.GetBlobContainerClient "data"
    let! blobs = container.GetBlobsAsync().AsTask()
}
```

## Pros and Cons 

The advantages of making this adjustment to F# are

* Better interop with other .NET libraries
* Consume asynchronous sequences
* Potentially the ability to create them as well

The disadvantages of making this adjustment to F# are

* Effort to create
* Currently not many .NET libraries use IAsyncEnumerable, although I expect this to grow over time

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): M

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

cc: @jongio

**Comment by Happypig375** [comment] 2021-01-31 15:43
Duplicate of https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1087-resumable-code-and-task-builder.md#example-taskseq---

**Comment by isaacabraham** [comment] 2021-01-31 15:55
Happy to close in favour of that. However, it may be that in the interim, an extension method similar to the example added above is added to FSharp.Core.

**Comment by Happypig375** [comment] 2021-01-31 15:59
Given that you can just copy that code, and that additions to FSharp.Core must stay forever, I doubt that we would want more useless extension methods like `AsyncRead` and `AsyncWrite`.

**Comment by Thorium** [comment] 2021-02-05 21:57
This shouldn't be F# but CLR/.NET thing. Currently libraries like EF implement their own versions, and LINQ wraps things with its non-async "SelectWhereWhateverEnumerable" wrappers, so it would be hard to gain benefits of the mechanism.

**Comment by bugproof** [comment] 2021-06-15 10:53
I think this adds support for it? https://github.com/fsprojects/FSharp.Control.AsyncSeq

**Comment by cartermp** [comment] 2021-06-15 15:28
I will close this in favor of the task RFC. It covers this scenario with `taskSeq`.

**Closed by cartermp** 2021-06-15 15:28 UTC

**Comment by Happypig375** [comment] 2021-06-15 15:42
Well, it's https://github.com/fsharp/fslang-design/pull/575 to be more precise, but that is pending.

**Comment by bugproof** [comment] 2021-06-15 15:46
Well FSharp.Control.AsyncSeq worked just fine in my case.

**Comment by cataggar** [comment] 2023-03-23 21:43
The NuGet package for `TaskSeq` was published in November 2022 here:
https://www.nuget.org/packages/FSharp.Control.TaskSeq/

@bugproof, a c[omparison with AsyncSeq](https://github.com/fsprojects/FSharp.Control.TaskSeq/#choosing-between-asyncseq-and-taskseq) is in their readme.
