### ISSUE TITLE
Provide better support for structural typing

### ISSUE THREAD

**Issue by baronfel** [fsharp/fslang-suggestions#298] opened 2016-10-20 02:43 UTC
**Submitted by Isaac Abraham on 7/16/2014 12:00:00 AM**  
**17 votes on UserVoice prior to migration**  

In F#3 you can declare a function which can operate on e.g. records which has no relation aside from the fact that they share e.g. field name + type. This can occasionally be useful - however, the syntax for achieving this is somewhat awkward e.g. http://codebetter.com/matthewpodwysocki/2009/06/11/f-duck-typing-and-structural-typing/

If there were a more succinct way to achieve this, it could be a very powerful feature.

**[Original UserVoice Submission](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6181848)**
[Archived Uservoice Comments](../tree/master/archive/suggestion-6181848-provide-better-support-for-structural-typing.md#comments)

**Comment by dsyme** [comment] 2016-10-29 17:28
Note this is related to #207

**Comment by dsyme** [comment] 2016-10-29 23:50
Despite the title this is really a duplicate of https://github.com/fsharp/fslang-suggestions/issues/440 when you look at the suggestion detail.

Closing for that reason. Other suggestions about structural typing are covered elsewhere.

**Closed by dsyme** 2016-10-29 23:50 UTC
Labels: old votes:11-50
