### ISSUE TITLE
Allow caret type parameters without space

### ISSUE THREAD

**Issue by Tarmil** [fsharp/fslang-suggestions#767] opened 2019-07-08 08:57 UTC
# Allow caret type parameters without space

Currently, when writing a statically-resolved type parameter (SRTP) between angle brackets, a space is necessary between the opening bracket and the caret so that `<^` isn't mistaken for a custom operator.

I propose we allow writing SRTPs as `A<^t>`.

The difficulty is that this is technically ambiguous, although only in very contrived situations:

```fsharp
let inline A<^T> (x: ^T) = x

let (<^) f x = f x

let inline ambiguous<^t when ^t : comparison> (t: ^t) (u: ^t) =
    A<^t> u
// The above could mean:
//    (A <^ t) > u
// or
//    (A< ^t>) (u)
```

Such a situation is highly unlikely to happen in practice, but it means that the compiler has to decide how to parse `<^`.

The simplest solution I can think of would be to parse it as an operator if it has whitespace before or after, and as SRTP if it doesn't have any whitespace around. General guidelines for operators are to surround them with spaces, so this should cover all usages.

## Pros and Cons 

The advantages of making this adjustment to F# are:

* More consistent (and slightly shorter) syntax for type parameters.
* One less confusing error message when using SRTP.

The disadvantages of making this adjustment to F# are:

* This is technically a breaking change, as some legit uses of the `(<^)` operator become syntax errors (or can even change semantics, as in the contrived example above).
* Yet another special case in the parser.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [ ] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by gusty** [comment] 2019-07-10 06:04
This is a dupe of #668 which is approved.

**Comment by Tarmil** [comment] 2019-07-10 07:51
Oops. I was surprised not to find it... In my defense it's hard to search for operators in GitHub 😕

**Comment by cartermp** [comment] 2019-07-10 16:16
Closing as dupe. No worries, @tarmil

**Closed by cartermp** 2019-07-10 16:16 UTC
