### ISSUE TITLE
Allow use of infix operators in pattern matching

### ISSUE THREAD

**Issue by lucasteles** [fsharp/fslang-suggestions#1130] opened 2022-04-16 14:25 UTC
# Allow use of infix operators in pattern matching

Today we have a limitation in pattern matching, If we try to use an infix operator  in a call to an active pattern, the compiler gives us `Unexpected infix operator in pattern.`

Given:
```fsharp
let (|Matches|_|) f x = if f x then Some () else None
let hasMaxLength size (s: string) = s.Length < size
let length = 10
```

This does *not* compile
```fsharp
let assertFoo = function
    | Matches (hasMaxLength (length + 1)) 
      & Matches (not << System.String.IsNullOrWhiteSpace)
        -> printfn "true"
    | _ -> printfn "false"

```

The alternative is to create a function or use the function form of the operator.

```fsharp
let assertFoo = function
    | Matches (hasMaxLength ((+) length 1)) 
      & Matches ((<<) not System.String.IsNullOrWhiteSpace)
        -> printfn "true"
    | _ -> printfn "false"
```

This could help other cases like #715 

## Pros and Cons 
The advantage of making this adjustment to F# is that is an expected behavior

I don't see any cons.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): 

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [X] This is not a breaking change to the F# language design
* [X] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by Happypig375** [comment] 2022-04-17 05:26
This can be considered as part of https://github.com/fsharp/fslang-suggestions/issues/1018

**Comment by cartermp** [comment] 2022-04-17 05:43
Will close as a duplicate of https://github.com/fsharp/fslang-suggestions/issues/1018, thanks @Happypig375

**Closed** 2022-04-18 12:17 UTC
