### ISSUE TITLE
Keyword const to replace use of Literal attribute

### ISSUE THREAD

**Issue by BentTranberg** [fsharp/fslang-suggestions#1061] opened 2021-08-15 09:57 UTC
# Keyword const to replace use of Literal attribute

I propose we introduce a `const` keyword to replace the use of the `[<Literal>]` attribute in declarations of constants. Instead of writing

`let [<Literal>] MyConstant = "yes"`

we should merely have to write

`const MyConstant = "yes"`

## Why?

First, when are constants needed? Constants declared with the Literal attribute are useful in connection with .NET interop. This is one example.

```
let [<Literal>] DllName = "some.dll"
[<DLLImport(DllName)>]
```

But constants declared with the Literal attribute are also useful in situations where .NET interop is not involved, and only pure F# code is involved. This is one example.

```
let [<Literal>] A = 1
let [<Literal>] B = 2

let f = function
    | A -> "one"
    | B -> "two"
    | _ -> "other"
```

If the Literal attribute was only relevant in .NET interop settings, I would not have authored this suggestion.

However, the second example illustrates why I believe a `const` keyword in the language is natural and favorable to the Literal attribute. This example relies specifically on the constants being exactly that, constants and not normal bindings. So the language itself relies on constants being constants in particular constructs, and therefore also relies on the ability to name constants.

There is also another issue that will be solved with this proposal. Code attributes are slightly troublesome because they are subject to _code drift_. Take the following example. We have a list of constants, like many programs has. Here the Literal attribute is used in the typical way that most developers are likely to write it, and not the more safe way used in the examples above. This heightens the risk of code drift considerably.

```
[<Literal>]
let Alpha = 1.2
let Gamma = 2.3 + initedZeta.Value
[<Literal>]
let Sigma7 = 3.4
```

Then somebody is in a hurry declaring a new constant Sigma3, and the next minute this is what we've got.

```
[<Literal>]
let Alpha = 1.2
let Gamma = 2.3 + initedZeta.Value
[<Literal>]
let Sigma3 = 5.6
let Sigma7 = 3.4
```

Can you spot the error introduced? This problem is called _code drift_. Changing Sigma7 was not intended.

Literal constants are far more susceptible to this kind of corruption than other language constructs, because they are often bundled together as shown in the example. It might not always be a critical error that results from code drift, but it is a change of meaning that could cause very hard to spot errors now, or at some point in the future. We like to think that F# is a language that lessen the risk of mistakes, including this kind of mistakes.

And I have one more argument. Binding is a runtime thing. Computations, if so only literal values, are bound at runtime with the let statement. Constants are named literals, and that makes it unnatural to use the let statement if one sees the let statement as a construct to bind.

## Pros and Cons 

The advantages of making this adjustment to F# are
* Easier to read syntax.
* More obvious what this language construct is.
* Similar to C#.
* Less use of code attributes. The Literal attribute is sometimes very heavily used, and it can look messy.
* Less risk of code drift.

The disadvantages of making this adjustment to F# are none that I can see. There seems to be very little risk of this keyword having any other obvious use that could get into conflict with this use.

## Extra information

Estimated cost (XS, S, M, L, XL, XXL):  XS

Related suggestions: None found.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

I have checked also the third above, because I have found no trace of any discussion, but suspect the current state is a decision that was made very early in F#s history, in the interest of being conservative with regards to changes that could conflict with C# or turn out negative in other ways. I suspect a final decision was left to the future, but probably nobody has seen any great need to make changes, and so everybody has gotten used to the Literal attribute.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [ ] I or my company would be willing to help implement and/or test this

I am a solo developer in a small company that is fighting to stay in business, and can't commit, so I can't check the last box, but I'm certainly interested in using this feature when it is available, and I do use preview versions of VS. In any case I assume this change has very little cost and need for testing.

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by cartermp** [comment] 2021-08-15 12:41
So weirdly enough, `const` is already used for this but only in the case of specifying a constant literal in a type provider argument in the `<...>`.

I personally think it would be neat to expand this out generally.

**Comment by Tarmil** [comment] 2021-08-15 15:40
@cartermp It feels different though. On one hand the current use of `const` is before an expression, it syntactically looks like a function call:

```fsharp
type MyJson = JsonProvider<const (__SOURCE_DIRECTORY__ + "/sample.json")>
```

On the other hand, this proposal would use it as a declaration keyword, like `let`, `type` or `member`.

I like the idea of the proposal, but I'm a bit wary of overloading the meaning of keywords like this 😕

**Comment by cartermp** [comment] 2021-08-15 20:42
Yeah, it's weird, although the type provider case is pretty obscure and so I'm not too worried.

**Comment by dsyme** [comment] 2021-08-16 11:35
This one was considered in F# 1.0/2.0.   The problem is that it is a false cogntate for F# - consider

```fsharp
const x1 = 1
let x2 = [1;2;3]
```
Here `x2` is just as constant as `x1` and the notion of things being constant and immutable is too important in F# to allow the keyword's use for something that is, from the F# perspective, primarily about the .NET representation of things. If anything in some far future revised F# it would be
```fsharp
literal x1 = 1
let x2 = [1;2;3]
```

but, as you know, that keyword is not reserved.

**Comment by dsyme** [comment] 2021-08-16 11:40
I could perhaps imagine this:
```fsharp
let literal x1 = 1
```

**Comment by Tarmil** [comment] 2021-08-16 14:01
Yeah I like `let literal`, if we're willing to make this kind of breaking change.

**Comment by dsyme** [comment] 2021-08-16 14:04
I mean, I'm not sold on this - `[<Literal>]` seems adequate and F# uses attributes like this in plenty of other ways. I get that the coding problems in the description are real enough

**Comment by BentTranberg** [comment] 2021-08-16 14:52
One can always put more effort into informing and advising about the `let [<Literal>]` syntax vs `[<Literal>] let` in documentation of various kinds, and even add checks for that in code analysis tools. Using the first syntax will practically eliminate the usual editing errors that results in code drift, because the attribute is inside rather than separate from the coding construct it affects. The usual editing problems are the one explained above, and also cut and/or paste where the `[<Literal>]` before `let` is overlooked and left behind during cut, possibly to affect another element.

Thanks for explaining about `literal` vs `const`. Had to think for a while, but I got the point in the end, and see why `literal` would be preferable.

I also see now why this innocent little suggestion is perhaps not such an innocent change after all, and may not be worth it.

**Comment by kspeakman** [comment] 2021-08-23 22:19
I also was ready to upvote. Being practiced in the distinction and use of `const` from C#, I used the literal attribute like I would const. But yeah I suppose it's unnecessary because it's already constant in how it is usable from F#. And the literal attribute is there if you want optimize for the compilation difference of const. Glad I read this issue.

**Comment by gusty** [comment] 2021-09-07 14:54
If we're sure we won't use `const` for stuff like this, can't we remove it from the reserved keyword list?

**Comment by dsyme** [comment] 2021-09-07 15:20
> If we're sure we won't use const for stuff like this, can't we remove it from the reserved keyword list?

It's used for static constant expressions provided as arguments to type providers.

In some distant future I could see us using it for defining a broader category of immutable/constant data.

**Comment by dsyme** [comment] 2023-01-09 23:31
Closing per my comments above

**Closed by dsyme** 2023-01-09 23:31 UTC
Labels: area: syntax
