### ISSUE TITLE
nameof with forward lookup (such as to members and parameters of the applied target)

### ISSUE THREAD

**Issue by Happypig375** [fsharp/fslang-suggestions#967] opened 2021-01-21 09:35 UTC
```fs
type [<Experimental(nameof W.M)>] W() = // FS0039 The type 'W' does not define the field, constructor or member 'M'.
                                        // FS0267 This is not a valid constant expression or custom attribute value
    static member M() = nameof W.M
```
C# allows this:
```cs
[System.Obsolete(nameof(M))] class W { static string M() => nameof(M); }
```

This is mentioned under [the RFC](https://github.com/fsharp/fslang-design/blob/master/FSharp-5.0/FS-1003-nameof-operator.md#scope-of-use) but makes this less useful.

While `nameof` to parameter names are currently not supported in C#, https://github.com/dotnet/csharplang/issues/373 is a championed issue in the C# team's Working Set which means that the C# team intends to add this feature. Since F# `nameof` imitates C# in terms of functionality, F# should support it too.

## Pros and Cons 

The advantage of making this adjustment to F# is fixing `nameof` to allow more use cases

The disadvantages of making this adjustment to F# are implementation complexity?

## Extra information

Estimated cost (XS, S, M, L, XL, XXL): S

Related suggestions: (put links to related suggestions here)

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

## For Readers

If you would like to see this issue implemented, please click the :+1: emoji on this issue. These counts are used to generally order the suggestions by engagement.

**Comment by charlesroddie** [comment] 2021-01-22 11:33
> Since F# nameof imitates C# in terms of functionality

I agree that nameof is a very C#ey feature, and as such I think it's premature to suggest something that C# hasn't implemented yet.

**Comment by Happypig375** [comment] 2021-01-22 15:11
While RFCs may need to wait for C#, the suggestion can still be made ahead of time to raise awareness.

**Comment by cartermp** [comment] 2021-01-22 15:42
This is highly unlikely to ever happen for F#. `nameof` is based on existing F# name resolution rules, which is by design. F# doesn't do forward lookup in name resolution. A special case here is not likely, and making it a generalized behavior is a far larger design task. I also suspect this is not a small thing to implement at all, even just for `nameof`.

**Comment by Happypig375** [comment] 2021-01-22 15:56
@cartermp This works:
```fs
Microsoft (R) F# Interactive version 11.0.0.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> type C() =
-     inherit ResizeArray<char>(nameof C.O)
-     let M = nameof C.O
-     member _.N = nameof C.O
-     static member O = nameof C.O;;
type C =
  class
    inherit ResizeArray<char>
    new : unit -> C
    member N : string
    static member O : string
  end
```
and it's inconsistent for attribute parameters for `type C()` to not resolve correctly.

**Comment by cartermp** [comment] 2021-01-22 16:03
Classes and members on them are not resolved in the same way (e.g., you can refer to things coming _after_ a member declaration inside of a class declaration if you have a handle on the self reference or it is static). It's also not forward-resolution.

> and it's inconsistent for attribute parameters for type C() to not resolve correctly.

Can you clarify what you mean?

**Comment by Happypig375** [comment] 2021-01-22 16:05
```fs
type [<Experimental(name C.O)>] C() = // Disallowed
     inherit ResizeArray<char>(nameof C.O)
     let M = nameof C.O
     member _.N = nameof C.O
     static member O = nameof C.O
```

**Comment by Happypig375** [comment] 2021-01-22 16:11
In the same vein, this should be allowed:
```fs
let [<Experimental(nameof f.x)>] f x = 3
```

**Comment by cartermp** [comment] 2021-01-22 16:15
I see. I don't see an inconsistency, since you can't resolve names like that in F# today. `nameof` is based on F# name resolution.

**Comment by Happypig375** [comment] 2021-01-22 16:16
```fs
type [<Experimental(nameof C)>] C() = // But this is OK!!
     inherit ResizeArray<char>(nameof C.O)
     let M = nameof C.O
     member _.N = nameof C.O
     static member O = nameof C.O
```

**Comment by Happypig375** [comment] 2021-07-25 17:07
https://github.com/dotnet/roslyn/pull/40525
C# is adding this.

**Comment by dsyme** [comment] 2022-06-14 16:09
I'm closing this as we decided not to do this in the RFC, and it just exposes us to too much new logic for nameof in a way that makes the feature as complex as F# name resolution itself, with many variations.

**Closed by dsyme** 2022-06-14 16:09 UTC
