### ISSUE TITLE
More "python-like" functionality for List/Array slice syntax

### ISSUE THREAD

**Issue by moonPtr** [fsharp/fslang-suggestions#662] opened 2018-04-20 21:38 UTC
Here's an example:
Let's say I want to get every nth element in an array. In python, that's a deliciously simple arr[::n]

Trying to achieve the same thing in F# is currently more than clumsy:
```fsharp
let everyNth n arr =
    arr
    |> Array.indexed
    |> Array.partition (fun (i, _) -> i % n = 0)
    |> fst
    |> Array.map snd
```
And this *only* covers the case of [::n]!

I would obviously love for F#'s slice syntax to become a bit more versatile

**Comment by abelbraaksma** [comment] 2018-04-20 23:37
Btw, I think we could certainly use `Array.filteri`, `Array.choosei`, `Array.wherei` etc, in line with `Array.iteri` and `Array.mapi`. With that in your standard library, it becomes a no-brainer:

```f#
let everyNth x = filteri (fun i _ -> i % x = 0)
```
But I would still favor some kind of syntax addition for slicing ;).

**Comment by theprash** [comment] 2018-04-22 10:36
Since `arr.[ 0 .. ]` is already valid syntax for, and since we already have step size in ranges - `[| 1 .. 3 .. 10 |]
` - I think the logical syntax for this would be `arr.[ 0 .. 3 .. ]`

However, I'm more in favour of adding `filteri`, `choosei` and `wherei` to `Array`, `List` and `Seq` because of the flexibility they would give. You could go further as there are more collection functions that take predicates: `tryFindi`, `tryPicki` etc.

**Comment by moonPtr** [comment] 2018-04-26 18:54
(@jwosty Thanks for the tip!)
I highly second @theprash's suggestion (and on a side-note, `tryPicki` sounds adorable.)

**Comment by moloneymb** [comment] 2018-10-03 00:29
@theprash One thing I'm looking at in my issue #701 is the use of this syntax in NDArrays where the axis of operation needs to be specified. In this case, would you swing back so that you could write expressions such as `rgb_small = bgra[NewAxis,10..-2..-10, 10..-2,..-10,[2,1,0]] ` ?

**Comment by cartermp** [comment] 2019-01-21 08:38
Closing this as a duplicate of:

* #358 - to support the specific concept of negative indices in slices
* #701 - to support steps in indices and Numpy-like slicing for N-dimensional arrays

**Closed by cartermp** 2019-01-21 08:38 UTC
